/**
 * Fallback snapshot of the Pokemon GO event list.
 *
 * GENERATED — do not hand-edit. Regenerate with: python3 scripts/update_events.py
 * Source: https://raw.githubusercontent.com/bigfoott/ScrapedDuck/data/events.json
 *         (ScrapedDuck, which scrapes https://leekduck.com/events/)
 * Fetched: 2026-09-11 21:34 local
 *
 * EVENTS ARE LIVE DATA. events.js fetches the feed above on every page load and renders
 * that; this file is only what it shows while the fetch is in flight or if it fails, and
 * the page says so on screen. Refreshing this file is not how the page stays current.
 *
 * caveats quote sentences from the event's page verbatim — the exclusive-move deadline, a
 * regional split, boosted Shiny odds, a debut, a bonus window that differs from the event's.
 * They are never composed here, only selected and labelled.
 *
 * blurb/has are scraped from each event's LeekDuck page — what the event actually is, and
 * what it contains. Events announced after this file was generated simply have neither, and
 * events.js falls back to its per-type explanation.
 *
 * start/end WITHOUT a trailing Z are local wall-clock times — 14:00 means 14:00 wherever
 * the player is. WITH a trailing Z they are real instants, which is how GO Battle League
 * rotations are published. events.js branches on the suffix; do not normalise it away.
 */

const EVENTS_FETCHED = "2026-09-11 21:34";
const EVENTS_SOURCE = "https://raw.githubusercontent.com/bigfoott/ScrapedDuck/data/events.json";

const EVENTS_SNAPSHOT = [
  {"id": "lego-pokemon-go-2026", "name": "LEGO Stores and Pokémon GO", "type": "event", "heading": "Event", "link": "https://leekduck.com/events/lego-pokemon-go-2026/", "start": "2026-08-03T10:00:00.000", "end": "2026-09-30T23:59:00.000", "blurb": "The Pokémon GO and LEGO Group partnership continues for Trainers in the US, UK, Poland, France, Germany, and Australia! Visit participating LEGO Store locations for raids, a LEGO-themed stamp rally, event stickers, and LEGO Pokémon SMART Play.", "has": ["raids", "research"]},
  {"id": "mega-beedrill-in-mega-raids-september-2026", "name": "Mega Beedrill in Mega Raids", "type": "raid-battles", "heading": "Raid Battles", "link": "https://leekduck.com/events/mega-beedrill-in-mega-raids-september-2026/", "start": "2026-09-08T06:00:00.000", "end": "2026-09-15T22:00:00.000", "mons": ["Mega Beedrill"], "has": ["raids", "shiny"]},
  {"id": "mega-squads", "name": "Mega Squads", "type": "event", "heading": "Event", "link": "https://leekduck.com/events/mega-squads/", "start": "2026-09-08T10:00:00.000", "end": "2026-09-14T20:00:00.000", "blurb": "Pick up where Mega Finale leaves off during Mega Squads, featuring the Pokémon GO debuts of Maschiff and Mabosstiff, the Shiny debut of Flamigo…", "has": ["bonuses", "spawns", "eggs", "raids", "research", "moves", "shiny"], "caveats": [{"k": "debut", "t": "Starting with the Mega Squads event, Mega Beedrill and Mega Houndoom can increase their Mega Level to Super Max for the first time in Pokémon GO!"}, {"k": "shiny", "t": "You’ll have an increased chance of encountering Shiny Pidgey from September 8 at 10:00 a.m. to September 11 at 10:00 a.m. local time."}]},
  {"id": "go-pass-september-2026", "name": "GO Pass: September", "type": "go-pass", "heading": "GO Pass", "link": "https://leekduck.com/events/go-pass-september-2026/", "start": "2026-09-08T10:00:00.000", "end": "2026-10-06T10:00:00.000", "blurb": "Latios soars in faster than a jet for GO Pass: September!"},
  {"id": "season-24-twilight-trails", "name": "Twilight Trails", "type": "season", "heading": "Season", "link": "https://leekduck.com/events/season-24-twilight-trails/", "start": "2026-09-08T10:00:00.000", "end": "2026-12-01T10:00:00.000", "blurb": "Welcome to Pokémon GO: Twilight Trails! In Pokémon GO, Seasons are periods of time that feature new events, Pokémon debuts, and surprises that all follow a certain theme.", "has": ["bonuses", "spawns", "eggs"]},
  {"id": "gbl-twilight-trails_great-league-mega-edition_ultra-league-mega-edition_master-league-mega-edition-split-1", "name": "Great League: Mega Edition, Ultra League: Mega Edition, and Master League: Mega Edition | Twilight Trails", "type": "go-battle-league", "heading": "GO Battle League", "link": "https://leekduck.com/events/gbl-twilight-trails_great-league-mega-edition_ultra-league-mega-edition_master-league-mega-edition-split-1/", "start": "2026-09-08T20:00:00.000Z", "end": "2026-09-15T20:00:00.000Z"},
  {"id": "zacian-hero-of-many-battles-in-5-star-raid-battles-september-2026", "name": "Zacian (Hero of Many Battles) in 5-star Raid Battles", "type": "raid-battles", "heading": "Raid Battles", "link": "https://leekduck.com/events/zacian-hero-of-many-battles-in-5-star-raid-battles-september-2026/", "start": "2026-09-09T06:00:00.000", "end": "2026-09-15T22:00:00.000", "mons": ["Zacian (Hero of Many Battles)"], "blurb": "There will also be a Raid Hour featuring Zacian (Hero of Many Battles) from 6:00 p.m. to 7:00 p.m. local time on September 9.", "has": ["raids", "shiny"]},
  {"id": "shadow-thundurus-incarnate-forme-in-shadow-raids-september-2026", "name": "Shadow Thundurus (Incarnate Forme) in Shadow Raids", "type": "raid-battles", "heading": "Raid Battles", "link": "https://leekduck.com/events/shadow-thundurus-incarnate-forme-in-shadow-raids-september-2026/", "start": "2026-09-09T06:00:00.000", "end": "2026-10-06T22:00:00.000", "mons": ["Thundurus (Incarnate)"], "blurb": "If you’re lucky, you may encounter Shiny Shadow Thundurus (Incarnate Forme)!", "has": ["raids", "shiny"]},
  {"id": "mega-houndoom-in-mega-raids-september-2026", "name": "Mega Houndoom in Mega Raids", "type": "raid-battles", "heading": "Raid Battles", "link": "https://leekduck.com/events/mega-houndoom-in-mega-raids-september-2026/", "start": "2026-09-11T06:00:00.000", "end": "2026-09-15T22:00:00.000", "mons": ["Mega Houndoom"], "has": ["raids", "shiny"]},
  {"id": "september-communitydayclassic2026", "name": "Gible Community Day Classic", "type": "community-day", "heading": "Community Day", "link": "https://leekduck.com/events/september-communitydayclassic2026/", "start": "2026-09-12T14:00:00.000", "end": "2026-09-12T17:00:00.000", "mons": ["Gible"], "bonuses": ["Increased Spawns", "3x Catch XP", "3-hour Incense*", "1-hour Lures**"], "blurb": "Gible, the Land Shark Pokémon, will be featured during September Community Day Classic!", "has": ["bonuses", "spawns", "research", "shiny"], "caveats": [{"k": "window", "t": "While most bonuses are only active during the three-hour event period, this bonus will be active from 2:00 p.m. to 9:00 p.m. local time."}, {"k": "move", "t": "Evolve Gabite (Gible’s Evolution) from the beginning of the event until September 12, 2026, at 9:00 p.m. local time to get a Garchomp that knows the Charged Attack Earth Power."}, {"k": "shiny", "t": "Gible attracted to regular Lure Modules will still have an increased chance to be Shiny and may have a Special Background."}]},
  {"id": "pokemonspotlighthour2026-09-13", "name": "Houndour and Houndoom Spotlight Hour", "type": "pokemon-spotlight-hour", "heading": "Pokémon Spotlight Hour", "link": "https://leekduck.com/events/pokemonspotlighthour2026-09-13/", "start": "2026-09-13T18:00:00.000", "end": "2026-09-13T19:00:00.000", "bonus": "2× Transfer Candy", "mons": ["Houndour", "Houndoom"]},
  {"id": "max-mondays-2026-09-14", "name": "Dynamax Rhyhorn during Max Monday", "type": "max-mondays", "heading": "Max Mondays", "link": "https://leekduck.com/events/max-mondays-2026-09-14/", "start": "2026-09-14T06:00:00.000", "end": "2026-09-14T21:00:00.000"},
  {"id": "gbl-twilight-trails_great-league_ultra-league-mega-edition_willpower-cup-great-league-edition", "name": "Great League, Ultra League: Mega Edition, and Willpower Cup: Great League Edition | Twilight Trails", "type": "go-battle-league", "heading": "GO Battle League", "link": "https://leekduck.com/events/gbl-twilight-trails_great-league_ultra-league-mega-edition_willpower-cup-great-league-edition/", "start": "2026-09-15T20:00:00.000Z", "end": "2026-09-22T20:00:00.000Z"},
  {"id": "mega-venusaur-in-mega-raids-september-2026", "name": "Mega Venusaur in Mega Raids", "type": "raid-battles", "heading": "Raid Battles", "link": "https://leekduck.com/events/mega-venusaur-in-mega-raids-september-2026/", "start": "2026-09-16T06:00:00.000", "end": "2026-09-22T22:00:00.000", "mons": ["Mega Venusaur"], "has": ["raids", "shiny"]},
  {"id": "zamazenta-hero-of-many-battles-in-5-star-raid-battles-september-2026", "name": "Zamazenta (Hero of Many Battles) in 5-star Raid Battles", "type": "raid-battles", "heading": "Raid Battles", "link": "https://leekduck.com/events/zamazenta-hero-of-many-battles-in-5-star-raid-battles-september-2026/", "start": "2026-09-16T06:00:00.000", "end": "2026-09-22T22:00:00.000", "mons": ["Zamazenta (Hero of Many Battles)"], "blurb": "There will also be a Raid Hour featuring Zamazenta (Hero of Many Battles) from 6:00 p.m. to 7:00 p.m. local time on September 16.", "has": ["raids", "shiny"]},
  {"id": "pokemon-horizons-the-series-celebration-event-2026", "name": "Pokémon Horizons: The Series Celebration Event", "type": "event", "heading": "Event", "link": "https://leekduck.com/events/pokemon-horizons-the-series-celebration-event-2026/", "start": "2026-09-16T10:00:00.000", "end": "2026-09-22T20:00:00.000", "blurb": "The Pokémon Horizons: The Series Celebration Event returns to Pokémon GO with the debut of Charmander wearing Friede’s goggles and its Evolutions! US fans can watch Pokémon Horizons: Season 3—Rising Hope on Netflix now.", "has": ["bonuses", "spawns", "raids", "research", "shiny"], "caveats": [{"k": "costume", "t": "A new costumed Pokémon will appear during this event!"}]},
  {"id": "raidhour20260916", "name": "Zamazenta (Hero of Many Battles) Raid Hour", "type": "raid-hour", "heading": "Raid Hour", "link": "https://leekduck.com/events/raidhour20260916/", "start": "2026-09-16T18:00:00.000", "end": "2026-09-16T19:00:00.000"},
  {"id": "pokemonspotlighthour2026-09-17", "name": "Mystery Pokémon Spotlight Hour", "type": "pokemon-spotlight-hour", "heading": "Pokémon Spotlight Hour", "link": "https://leekduck.com/events/pokemonspotlighthour2026-09-17/", "start": "2026-09-17T18:00:00.000", "end": "2026-09-17T19:00:00.000"},
  {"id": "staraptor-super-mega-raid-day-2026", "name": "Staraptor Super Mega Raid Day", "type": "raid-day", "heading": "Raid Day", "link": "https://leekduck.com/events/staraptor-super-mega-raid-day-2026/", "start": "2026-09-19T14:00:00.000", "end": "2026-09-19T17:00:00.000", "blurb": "Ready yourself to courageously challenge Staraptor Super Mega Raid Day!", "has": ["bonuses", "raids", "research", "shiny"], "caveats": [{"k": "debut", "t": "The following Pokémon will make its Pokémon GO debut in Super Mega Raids!"}, {"k": "shiny", "t": "Trainers will have an increased chance of encountering Shiny Staraptor from Super Mega Raids."}]},
  {"id": "max-mondays-2026-09-21", "name": "Dynamax Articuno, Zapdos, and Moltres during Max Monday", "type": "max-mondays", "heading": "Max Mondays", "link": "https://leekduck.com/events/max-mondays-2026-09-21/", "start": "2026-09-21T06:00:00.000", "end": "2026-09-21T21:00:00.000"},
  {"id": "gbl-twilight-trails_ultra-league_master-league-mega-edition_retro-cup-great-league-edition", "name": "Ultra League, Master League: Mega Edition, and Retro Cup: Great League Edition | Twilight Trails", "type": "go-battle-league", "heading": "GO Battle League", "link": "https://leekduck.com/events/gbl-twilight-trails_ultra-league_master-league-mega-edition_retro-cup-great-league-edition/", "start": "2026-09-22T20:00:00.000Z", "end": "2026-09-29T20:00:00.000Z"},
  {"id": "mega-malamar-in-mega-raids-september-2026", "name": "Mega Malamar in Mega Raids", "type": "raid-battles", "heading": "Raid Battles", "link": "https://leekduck.com/events/mega-malamar-in-mega-raids-september-2026/", "start": "2026-09-23T06:00:00.000", "end": "2026-09-29T22:00:00.000", "mons": ["Mega Malamar"], "has": ["raids", "shiny"]},
  {"id": "xurkitree-pheromosa-buzzwole-in-5-star-raid-battles-september-2026", "name": "Xurkitree, Pheromosa, and Buzzwole in 5-star Raid Battles", "type": "raid-battles", "heading": "Raid Battles", "link": "https://leekduck.com/events/xurkitree-pheromosa-buzzwole-in-5-star-raid-battles-september-2026/", "start": "2026-09-23T06:00:00.000", "end": "2026-09-29T22:00:00.000", "mons": ["Buzzwole", "Pheromosa", "Xurkitree"], "blurb": "Xurkitree will appear in the Asia-Pacific region, Pheromosa will appear in Europe, the Middle East, Africa, and India, and Buzzwole will appear in the Americas and Greenland. There will also be a Raid Hour featuring these regional raid bosses from…", "has": ["raids", "shiny"], "caveats": [{"k": "regional", "t": "Xurkitree will appear in the Asia-Pacific region, Pheromosa will appear in Europe, the Middle East, Africa, and India, and Buzzwole will appear in the Americas and Greenland."}]},
  {"id": "raidhour20260923", "name": "Xurkitree, Pheromosa, and Buzzwole Raid Hour", "type": "raid-hour", "heading": "Raid Hour", "link": "https://leekduck.com/events/raidhour20260923/", "start": "2026-09-23T18:00:00.000", "end": "2026-09-23T19:00:00.000"},
  {"id": "pokemonspotlighthour2026-09-24", "name": "Rattata Spotlight Hour", "type": "pokemon-spotlight-hour", "heading": "Pokémon Spotlight Hour", "link": "https://leekduck.com/events/pokemonspotlighthour2026-09-24/", "start": "2026-09-24T18:00:00.000", "end": "2026-09-24T19:00:00.000", "bonus": "2× Evolution XP", "mons": ["Rattata"]},
  {"id": "catch-mastery-phantump-2026", "name": "Phantump Catch Mastery", "type": "event", "heading": "Event", "link": "https://leekduck.com/events/catch-mastery-phantump-2026/", "start": "2026-09-26T10:00:00.000", "end": "2026-09-26T20:00:00.000", "blurb": "Get ready for a Catch Mastery event featuring Phantump, the Stump Pokémon!", "has": ["bonuses", "spawns", "research", "shiny"], "caveats": [{"k": "shiny", "t": "You’ll have an increased chance of encountering Shiny Phantump!"}]},
  {"id": "max-mondays-2026-09-28", "name": "Dynamax Sobble during Max Monday", "type": "max-mondays", "heading": "Max Mondays", "link": "https://leekduck.com/events/max-mondays-2026-09-28/", "start": "2026-09-28T06:00:00.000", "end": "2026-09-28T21:00:00.000"},
  {"id": "harvest-festival-2026", "name": "Harvest Festival 2026: Applin Picking", "type": "event", "heading": "Event", "link": "https://leekduck.com/events/harvest-festival-2026/", "start": "2026-09-29T10:00:00.000", "end": "2026-10-05T20:00:00.000", "blurb": "Harvest Festival returns with the Pokémon GO debut of Shiny Applin! Gather apples, choose a Timed Research path, and earn rewards through the event GO Pass.", "has": ["bonuses", "spawns", "research", "shiny"], "caveats": [{"k": "debut", "t": "Harvest Festival returns with the Pokémon GO debut of Shiny Applin!"}, {"k": "costume", "t": "Tap these apples to receive Tart Apples, Sweet Apples, Syrupy Apples, or encounters with event-themed Pokémon, including Cottonee wearing a flower crown and Applin!"}, {"k": "shiny", "t": "Shiny Applin will be available for the first time in Pokémon GO!"}]},
  {"id": "gbl-twilight-trails_master-league_mega-color-cup-great-league-edition", "name": "Master League and Mega Color Cup: Great League Edition | Twilight Trails", "type": "go-battle-league", "heading": "GO Battle League", "link": "https://leekduck.com/events/gbl-twilight-trails_master-league_mega-color-cup-great-league-edition/", "start": "2026-09-29T20:00:00.000Z", "end": "2026-10-06T20:00:00.000Z"},
  {"id": "mega-victreebel-in-mega-raids-september-2026", "name": "Mega Victreebel in Mega Raids", "type": "raid-battles", "heading": "Raid Battles", "link": "https://leekduck.com/events/mega-victreebel-in-mega-raids-september-2026/", "start": "2026-09-30T06:00:00.000", "end": "2026-10-06T22:00:00.000", "mons": ["Mega Victreebel"], "has": ["raids", "shiny"]},
  {"id": "xerneas-in-5-star-raid-battles-september-2026", "name": "Xerneas in 5-star Raid Battles", "type": "raid-battles", "heading": "Raid Battles", "link": "https://leekduck.com/events/xerneas-in-5-star-raid-battles-september-2026/", "start": "2026-09-30T06:00:00.000", "end": "2026-10-06T22:00:00.000", "mons": ["Xerneas"], "blurb": "There will also be a Raid Hour featuring Xerneas from 6:00 p.m. to 7:00 p.m. local time on September 30.", "has": ["raids", "shiny"]},
  {"id": "raidhour20260930", "name": "Xerneas Raid Hour", "type": "raid-hour", "heading": "Raid Hour", "link": "https://leekduck.com/events/raidhour20260930/", "start": "2026-09-30T18:00:00.000", "end": "2026-09-30T19:00:00.000"},
  {"id": "harvest-festival-taken-over-2026", "name": "Harvest Festival: Taken Over", "type": "event", "heading": "Event", "link": "https://leekduck.com/events/harvest-festival-taken-over-2026/", "start": "2026-10-02T00:00:00.000", "end": "2026-10-05T20:00:00.000", "blurb": "Rescue Shadow Zekrom, battle new Shadow Pokémon, and hatch Shiny Shroodle during Harvest Festival: Taken Over!", "has": ["bonuses", "spawns", "research", "shiny"], "caveats": [{"k": "shiny", "t": "Shiny Shroodle will be available to hatch for the first time in Pokémon GO!"}]},
  {"id": "patterns-of-the-wild-2026", "name": "Patterns of the Wild", "type": "event", "heading": "Event", "link": "https://leekduck.com/events/patterns-of-the-wild-2026/", "start": "2026-10-02T10:00:00.000", "end": "2026-10-02T20:00:00.000", "blurb": "This event is available only in Indonesia. Note: The original announcement was updated to say this event is exclusive to Indonesia.", "has": ["bonuses", "spawns", "research", "shiny"], "caveats": [{"k": "costume", "t": "Patterns of the Wild brings a Special Background for Pikachu wearing a batik shirt, along with boosted wild encounters, Incense bonuses, and research rewards!"}, {"k": "debut", "t": "Pikachu wearing a batik shirt can have a Special Background for the first time in Pokémon GO!"}, {"k": "shiny", "t": "These Pokémon will appear more often in the wild, with an increased chance of encountering their Shiny variants."}]},
  {"id": "gigantamax-cinderace-max-battle-day-2026", "name": "Gigantamax Cinderace Max Battle Day", "type": "max-battles", "heading": "Max Battles", "link": "https://leekduck.com/events/gigantamax-cinderace-max-battle-day-2026/", "start": "2026-10-03T14:00:00.000", "end": "2026-10-03T17:00:00.000", "blurb": "Shiny Gigantamax Cinderace makes its Pokémon GO debut in six-star Max Battles!", "has": ["bonuses", "research", "shiny"], "caveats": [{"k": "debut", "t": "For the first time in Pokémon GO, you’ll be able to encounter Shiny Gigantamax Cinderace—if you’re lucky!"}]},
  {"id": "gbl-twilight-trails_great-league-mega-edition_ultra-league-mega-edition_master-league-mega-edition-split-2", "name": "Great League: Mega Edition, Ultra League: Mega Edition, and Master League: Mega Edition | Twilight Trails", "type": "go-battle-league", "heading": "GO Battle League", "link": "https://leekduck.com/events/gbl-twilight-trails_great-league-mega-edition_ultra-league-mega-edition_master-league-mega-edition-split-2/", "start": "2026-10-06T20:00:00.000Z", "end": "2026-10-13T20:00:00.000Z"},
  {"id": "october-communityday2026", "name": "October Community Day", "type": "community-day", "heading": "Community Day", "link": "https://leekduck.com/events/october-communityday2026/", "start": "2026-10-10T14:00:00.000", "end": "2026-10-10T17:00:00.000"},
  {"id": "gbl-twilight-trails_great-league_ultra-league-mega-edition_little-cup", "name": "Great League, Ultra League: Mega Edition, and Little Cup | Twilight Trails", "type": "go-battle-league", "heading": "GO Battle League", "link": "https://leekduck.com/events/gbl-twilight-trails_great-league_ultra-league-mega-edition_little-cup/", "start": "2026-10-13T20:00:00.000Z", "end": "2026-10-20T20:00:00.000Z"},
  {"id": "hatch-day-october-2026", "name": "Hatch Day", "type": "event", "heading": "Event", "link": "https://leekduck.com/events/hatch-day-october-2026/", "start": "2026-10-17T11:00:00.000", "end": "2026-10-17T17:00:00.000"},
  {"id": "gbl-twilight-trails_ultra-league_master-league-mega-edition_fantasy-cup-great-league-edition", "name": "Ultra League, Master League: Mega Edition, and Fantasy Cup: Great League Edition | Twilight Trails", "type": "go-battle-league", "heading": "GO Battle League", "link": "https://leekduck.com/events/gbl-twilight-trails_ultra-league_master-league-mega-edition_fantasy-cup-great-league-edition/", "start": "2026-10-20T20:00:00.000Z", "end": "2026-10-27T20:00:00.000Z"},
  {"id": "max-battle-day-october-24-2026", "name": "Max Battle Day", "type": "max-battles", "heading": "Max Battles", "link": "https://leekduck.com/events/max-battle-day-october-24-2026/", "start": "2026-10-24T14:00:00.000", "end": "2026-10-24T17:00:00.000"},
  {"id": "gbl-twilight-trails_master-league_mega-halloween-cup-great-league-edition", "name": "Master League and Mega Halloween Cup: Great League Edition | Twilight Trails", "type": "go-battle-league", "heading": "GO Battle League", "link": "https://leekduck.com/events/gbl-twilight-trails_master-league_mega-halloween-cup-great-league-edition/", "start": "2026-10-27T21:00:00.000Z", "end": "2026-11-03T21:00:00.000Z"},
  {"id": "super-mega-raid-day-october-2026", "name": "Super Mega Raid Day", "type": "raid-day", "heading": "Raid Day", "link": "https://leekduck.com/events/super-mega-raid-day-october-2026/", "start": "2026-10-31T14:00:00.000", "end": "2026-10-31T17:00:00.000"},
  {"id": "gbl-twilight-trails_great-league-mega-edition_ultra-league-mega-edition_master-league-mega-edition-split-3", "name": "Great League: Mega Edition, Ultra League: Mega Edition, and Master League: Mega Edition | Twilight Trails", "type": "go-battle-league", "heading": "GO Battle League", "link": "https://leekduck.com/events/gbl-twilight-trails_great-league-mega-edition_ultra-league-mega-edition_master-league-mega-edition-split-3/", "start": "2026-11-03T21:00:00.000Z", "end": "2026-11-10T21:00:00.000Z"},
  {"id": "pokemon-go-wild-area-2026-sendai-japan", "name": "Pokémon GO Wild Area 2026: Sendai • Tohoku", "type": "wild-area", "heading": "Wild Area", "link": "https://leekduck.com/events/pokemon-go-wild-area-2026-sendai-japan/", "start": "2026-11-06T01:00:00.000Z", "end": "2026-11-08T09:00:00.000Z"},
  {"id": "pokemon-go-wild-area-2026-mexico-city", "name": "Pokémon GO Wild Area 2026: Mexico City", "type": "wild-area", "heading": "Wild Area", "link": "https://leekduck.com/events/pokemon-go-wild-area-2026-mexico-city/", "start": "2026-11-06T16:00:00.000Z", "end": "2026-11-09T00:00:00.000Z"},
  {"id": "gbl-twilight-trails_great-league_ultra-league-mega-edition_2026-go-laic-cup", "name": "Great League, Ultra League: Mega Edition, and 2026 GO LAIC Cup | Twilight Trails", "type": "go-battle-league", "heading": "GO Battle League", "link": "https://leekduck.com/events/gbl-twilight-trails_great-league_ultra-league-mega-edition_2026-go-laic-cup/", "start": "2026-11-10T21:00:00.000Z", "end": "2026-11-17T21:00:00.000Z"},
  {"id": "pokemon-go-wild-area-2026-global", "name": "Pokémon GO Wild Area 2026: Global", "type": "wild-area", "heading": "Wild Area", "link": "https://leekduck.com/events/pokemon-go-wild-area-2026-global/", "start": "2026-11-14T10:00:00.000", "end": "2026-11-15T18:00:00.000"},
  {"id": "gbl-twilight-trails_ultra-league_master-league-mega-edition_2026-go-laic-cup", "name": "Ultra League, Master League: Mega Edition, and 2026 GO LAIC Cup | Twilight Trails", "type": "go-battle-league", "heading": "GO Battle League", "link": "https://leekduck.com/events/gbl-twilight-trails_ultra-league_master-league-mega-edition_2026-go-laic-cup/", "start": "2026-11-18T21:00:00.000Z", "end": "2026-11-25T21:00:00.000Z"},
  {"id": "november-communityday2026", "name": "November Community Day", "type": "community-day", "heading": "Community Day", "link": "https://leekduck.com/events/november-communityday2026/", "start": "2026-11-21T14:00:00.000", "end": "2026-11-21T17:00:00.000"},
  {"id": "gbl-twilight-trails_master-league_mega-catch-cup-great-league-edition", "name": "Master League and Mega Catch Cup: Great League Edition | Twilight Trails", "type": "go-battle-league", "heading": "GO Battle League", "link": "https://leekduck.com/events/gbl-twilight-trails_master-league_mega-catch-cup-great-league-edition/", "start": "2026-11-24T21:00:00.000Z", "end": "2026-12-01T21:00:00.000Z"},
  {"id": "super-mega-raid-day-november-2026", "name": "Super Mega Raid Day", "type": "raid-day", "heading": "Raid Day", "link": "https://leekduck.com/events/super-mega-raid-day-november-2026/", "start": "2026-11-28T14:00:00.000", "end": "2026-11-28T17:00:00.000"}
];
