/**
 * All released Dynamax and Gigantamax Pokemon in Pokemon GO.
 *
 * GENERATED — do not hand-edit. Regenerate with: python3 scripts/update_dynamax.py
 * Sources: https://bulbapedia.bulbagarden.net/wiki/Dynamax_(GO)
 *          https://bulbapedia.bulbagarden.net/wiki/Gigantamax_(GO)
 *
 * A Gigantamax form is tracked separately from its Dynamax entry — they are different
 * catches. hasGmax marks a Dynamax entry whose species also has a Gigantamax form.
 *
 * raid/stars is stored for Gigantamax only, where the battle is always a six-star
 * Gigantamax Max Battle (https://bulbapedia.bulbagarden.net/wiki/Max_Battle). The tier of a
 * plain Dynamax Pokemon belongs to the current Power Spot rotation rather than the species,
 * rotates weekly, and is deliberately NOT stored — it would be stale within days.
 */

const GIGANTAMAX = [
  {"name": "Venusaur", "art": "venusaur-gigantamax", "gmaxMove": "G-Max Vine Lash", "raid": "Gigantamax Battle", "stars": 6, "released": "October 26, 2024"},
  {"name": "Charizard", "art": "charizard-gigantamax", "gmaxMove": "G-Max Wildfire", "raid": "Gigantamax Battle", "stars": 6, "released": "October 26, 2024"},
  {"name": "Blastoise", "art": "blastoise-gigantamax", "gmaxMove": "G-Max Cannonade", "raid": "Gigantamax Battle", "stars": 6, "released": "October 26, 2024"},
  {"name": "Butterfree", "art": "butterfree-gigantamax", "gmaxMove": "G-Max Befuddle", "raid": "Gigantamax Battle", "stars": 6, "released": "August 3, 2025"},
  {"name": "Pikachu", "art": "pikachu-gigantamax", "gmaxMove": "G-Max Volt Crash", "raid": "Gigantamax Battle", "stars": 6, "released": "March 28, 2026"},
  {"name": "Meowth", "art": "meowth-gigantamax", "gmaxMove": "G-Max Gold Rush", "raid": "Gigantamax Battle", "stars": 6, "released": "February 15, 2026"},
  {"name": "Machamp", "art": "machamp-gigantamax", "gmaxMove": "G-Max Chi Strike", "raid": "Gigantamax Battle", "stars": 6, "released": "May 25, 2025"},
  {"name": "Gengar", "art": "gengar-gigantamax", "gmaxMove": "G-Max Terror", "raid": "Gigantamax Battle", "stars": 6, "released": "October 31, 2024"},
  {"name": "Kingler", "art": "kingler-gigantamax", "gmaxMove": "G-Max Foam Burst", "raid": "Gigantamax Battle", "stars": 6, "released": "February 1, 2025"},
  {"name": "Lapras", "art": "lapras-gigantamax", "gmaxMove": "G-Max Resonance", "raid": "Gigantamax Battle", "stars": 6, "released": "December 8, 2024"},
  {"name": "Snorlax", "art": "snorlax-gigantamax", "gmaxMove": "G-Max Replenish", "raid": "Gigantamax Battle", "stars": 6, "released": "April 19, 2025"},
  {"name": "Garbodor", "art": "garbodor-gigantamax", "gmaxMove": "G-Max Malodor", "raid": "Gigantamax Battle", "stars": 6, "released": "November 1, 2025"},
  {"name": "Rillaboom", "art": "rillaboom-gigantamax", "gmaxMove": "G-Max Drum Solo", "raid": "Gigantamax Battle", "stars": 6, "released": "May 29, 2025"},
  {"name": "Cinderace", "art": "cinderace-gigantamax", "gmaxMove": "G-Max Fireball", "raid": "Gigantamax Battle", "stars": 6, "released": "June 5, 2025"},
  {"name": "Inteleon", "art": "inteleon-gigantamax", "gmaxMove": "G-Max Hydrosnipe", "raid": "Gigantamax Battle", "stars": 6, "released": "June 12, 2025"},
  {"name": "Toxtricity", "art": "toxtricity-gigantamax", "gmaxMove": "G-Max Stun Shock", "raid": "Gigantamax Battle", "stars": 6, "released": "November 16, 2024"},
  {"name": "Grimmsnarl", "art": "grimmsnarl-gigantamax", "gmaxMove": "G-Max Snooze", "raid": "Gigantamax Battle", "stars": 6, "released": "November 7, 2025"}
];

const DYNAMAX = [
  {"name": "Wooloo", "art": "wooloo", "released": "Sep 4, 2024"},
  {"name": "Dubwool", "art": "dubwool", "released": "Sep 4, 2024"},
  {"name": "Skwovet", "art": "skwovet", "released": "Sep 4, 2024"},
  {"name": "Greedent", "art": "greedent", "released": "Sep 4, 2024"},
  {"name": "Bulbasaur", "art": "bulbasaur", "released": "Sep 10, 2024"},
  {"name": "Ivysaur", "art": "ivysaur", "released": "Sep 10, 2024"},
  {"name": "Venusaur", "art": "venusaur", "released": "Sep 10, 2024", "hasGmax": true},
  {"name": "Charmander", "art": "charmander", "released": "Sep 10, 2024"},
  {"name": "Charmeleon", "art": "charmeleon", "released": "Sep 10, 2024"},
  {"name": "Charizard", "art": "charizard", "released": "Sep 10, 2024", "hasGmax": true},
  {"name": "Squirtle", "art": "squirtle", "released": "Sep 10, 2024"},
  {"name": "Wartortle", "art": "wartortle", "released": "Sep 10, 2024"},
  {"name": "Blastoise", "art": "blastoise", "released": "Sep 10, 2024", "hasGmax": true},
  {"name": "Beldum", "art": "beldum", "released": "Sep 18, 2024"},
  {"name": "Metang", "art": "metang", "released": "Sep 18, 2024"},
  {"name": "Metagross", "art": "metagross", "released": "Sep 18, 2024"},
  {"name": "Grookey", "art": "grookey", "released": "Oct 1, 2024"},
  {"name": "Thwackey", "art": "thwackey", "released": "Oct 1, 2024"},
  {"name": "Rillaboom", "art": "rillaboom", "released": "Oct 1, 2024", "hasGmax": true},
  {"name": "Scorbunny", "art": "scorbunny", "released": "Oct 1, 2024"},
  {"name": "Raboot", "art": "raboot", "released": "Oct 1, 2024"},
  {"name": "Cinderace", "art": "cinderace", "released": "Oct 1, 2024", "hasGmax": true},
  {"name": "Sobble", "art": "sobble", "released": "Oct 1, 2024"},
  {"name": "Drizzile", "art": "drizzile", "released": "Oct 1, 2024"},
  {"name": "Inteleon", "art": "inteleon", "released": "Oct 1, 2024", "hasGmax": true},
  {"name": "Falinks", "art": "falinks", "released": "Oct 1, 2024"},
  {"name": "Gastly", "art": "gastly", "released": "Oct 22, 2024"},
  {"name": "Haunter", "art": "haunter", "released": "Oct 22, 2024"},
  {"name": "Gengar", "art": "gengar", "released": "Oct 22, 2024", "hasGmax": true},
  {"name": "Drilbur", "art": "drilbur", "released": "Nov 15, 2024"},
  {"name": "Excadrill", "art": "excadrill", "released": "Nov 15, 2024"},
  {"name": "Toxtricity", "art": "toxtricity-amped", "released": "Nov 16, 2024", "form": "Amped Form", "hasGmax": true},
  {"name": "Toxtricity", "art": "toxtricity-low-key", "released": "Nov 16, 2024", "form": "Low Key Form", "hasGmax": true},
  {"name": "Machop", "art": "machop", "released": "Dec 3, 2024"},
  {"name": "Machoke", "art": "machoke", "released": "Dec 3, 2024"},
  {"name": "Machamp", "art": "machamp", "released": "Dec 3, 2024", "hasGmax": true},
  {"name": "Krabby", "art": "krabby", "released": "Dec 9, 2024"},
  {"name": "Kingler", "art": "kingler", "released": "Dec 9, 2024", "hasGmax": true},
  {"name": "Cryogonal", "art": "cryogonal", "released": "Dec 23, 2024"},
  {"name": "Articuno", "art": "articuno", "released": "Jan 20, 2025"},
  {"name": "Zapdos", "art": "zapdos", "released": "Jan 27, 2025"},
  {"name": "Moltres", "art": "moltres", "released": "Feb 3, 2025"},
  {"name": "Pidove", "art": "pidove", "released": "Feb 17, 2025"},
  {"name": "Tranquill", "art": "tranquill", "released": "Feb 17, 2025"},
  {"name": "Unfezant", "art": "unfezant", "released": "Feb 17, 2025"},
  {"name": "Darumaka", "art": "darumaka", "released": "Feb 24, 2025"},
  {"name": "Darmanitan", "art": "darmanitan", "released": "Feb 24, 2025"},
  {"name": "Kubfu", "art": "kubfu", "released": "Mar 5, 2025"},
  {"name": "Raikou", "art": "raikou", "released": "Mar 15, 2025"},
  {"name": "Chansey", "art": "chansey", "released": "Mar 17, 2025"},
  {"name": "Blissey", "art": "blissey", "released": "Mar 17, 2025"},
  {"name": "Caterpie", "art": "caterpie", "released": "Mar 24, 2025"},
  {"name": "Metapod", "art": "metapod", "released": "Mar 24, 2025"},
  {"name": "Butterfree", "art": "butterfree", "released": "Mar 24, 2025", "hasGmax": true},
  {"name": "Passimian", "art": "passimian", "released": "Apr 7, 2025"},
  {"name": "Entei", "art": "entei", "released": "Apr 26, 2025"},
  {"name": "Suicune", "art": "suicune", "released": "May 10, 2025"},
  {"name": "Sableye", "art": "sableye", "released": "May 19, 2025"},
  {"name": "Urshifu", "art": "urshifu-single-strike", "released": "May 21, 2025", "form": "Single Strike Style"},
  {"name": "Urshifu", "art": "urshifu-rapid-strike", "released": "May 21, 2025", "form": "Rapid Strike Style"},
  {"name": "Rookidee", "art": "rookidee", "released": "May 26, 2025"},
  {"name": "Corvisquire", "art": "corvisquire", "released": "May 26, 2025"},
  {"name": "Corviknight", "art": "corviknight", "released": "May 26, 2025"},
  {"name": "Hatenna", "art": "hatenna", "released": "Jun 16, 2025"},
  {"name": "Hattrem", "art": "hattrem", "released": "Jun 16, 2025"},
  {"name": "Hatterene", "art": "hatterene", "released": "Jun 16, 2025"},
  {"name": "Shuckle", "art": "shuckle", "released": "Jun 30, 2025"},
  {"name": "Wailmer", "art": "wailmer", "released": "Jul 14, 2025"},
  {"name": "Wailord", "art": "wailord", "released": "Jul 14, 2025"},
  {"name": "Latias", "art": "latias", "released": "Jul 26, 2025"},
  {"name": "Latios", "art": "latios", "released": "Jul 26, 2025"},
  {"name": "Kabuto", "art": "kabuto", "released": "Jul 28, 2025"},
  {"name": "Kabutops", "art": "kabutops", "released": "Jul 28, 2025"},
  {"name": "Omanyte", "art": "omanyte", "released": "Aug 4, 2025"},
  {"name": "Omastar", "art": "omastar", "released": "Aug 4, 2025"},
  {"name": "Trubbish", "art": "trubbish", "released": "Aug 11, 2025"},
  {"name": "Garbodor", "art": "garbodor", "released": "Aug 11, 2025", "hasGmax": true},
  {"name": "Abra", "art": "abra", "released": "Sep 15, 2025"},
  {"name": "Kadabra", "art": "kadabra", "released": "Sep 15, 2025"},
  {"name": "Alakazam", "art": "alakazam", "released": "Sep 15, 2025"},
  {"name": "Duraludon", "art": "duraludon", "released": "Sep 30, 2025"},
  {"name": "Bounsweet", "art": "bounsweet", "released": "Oct 13, 2025"},
  {"name": "Steenee", "art": "steenee", "released": "Oct 13, 2025"},
  {"name": "Tsareena", "art": "tsareena", "released": "Oct 13, 2025"},
  {"name": "Woobat", "art": "woobat", "released": "Oct 27, 2025"},
  {"name": "Swoobat", "art": "swoobat", "released": "Oct 27, 2025"},
  {"name": "Inkay", "art": "inkay", "released": "Nov 3, 2025"},
  {"name": "Malamar", "art": "malamar", "released": "Nov 3, 2025"},
  {"name": "Ralts", "art": "ralts", "released": "Nov 10, 2025"},
  {"name": "Kirlia", "art": "kirlia", "released": "Nov 10, 2025"},
  {"name": "Gardevoir", "art": "gardevoir", "released": "Nov 10, 2025"},
  {"name": "Gallade", "art": "gallade", "released": "Nov 10, 2025"},
  {"name": "Eevee", "art": "eevee", "released": "Nov 24, 2025"},
  {"name": "Vaporeon", "art": "vaporeon", "released": "Nov 24, 2025"},
  {"name": "Jolteon", "art": "jolteon", "released": "Nov 24, 2025"},
  {"name": "Flareon", "art": "flareon", "released": "Nov 24, 2025"},
  {"name": "Espeon", "art": "espeon", "released": "Nov 24, 2025"},
  {"name": "Umbreon", "art": "umbreon", "released": "Nov 24, 2025"},
  {"name": "Leafeon", "art": "leafeon", "released": "Nov 24, 2025"},
  {"name": "Glaceon", "art": "glaceon", "released": "Nov 24, 2025"},
  {"name": "Sylveon", "art": "sylveon", "released": "Nov 24, 2025"},
  {"name": "Lugia", "art": "lugia", "released": "Nov 29, 2025"},
  {"name": "Hitmonlee", "art": "hitmonlee", "released": "Dec 11, 2025"},
  {"name": "Hitmonchan", "art": "hitmonchan", "released": "Dec 11, 2025"},
  {"name": "Spheal", "art": "spheal", "released": "Dec 22, 2025"},
  {"name": "Sealeo", "art": "sealeo", "released": "Dec 22, 2025"},
  {"name": "Walrein", "art": "walrein", "released": "Dec 22, 2025"},
  {"name": "Drampa", "art": "drampa", "released": "Jan 5, 2026"},
  {"name": "Roggenrola", "art": "roggenrola", "released": "Jan 26, 2026"},
  {"name": "Boldore", "art": "boldore", "released": "Jan 26, 2026"},
  {"name": "Gigalith", "art": "gigalith", "released": "Jan 26, 2026"},
  {"name": "Ho-Oh", "art": "ho-oh", "released": "Jan 31, 2026"},
  {"name": "Growlithe", "art": "growlithe", "released": "Feb 9, 2026"},
  {"name": "Arcanine", "art": "arcanine", "released": "Feb 9, 2026"},
  {"name": "Pikachu", "art": "pikachu", "released": "Mar 9, 2026", "hasGmax": true},
  {"name": "Raichu", "art": "raichu", "released": "Mar 9, 2026"},
  {"name": "Regice", "art": "regice", "released": "Mar 23, 2026"},
  {"name": "Trapinch", "art": "trapinch", "released": "Apr 6, 2026"},
  {"name": "Vibrava", "art": "vibrava", "released": "Apr 6, 2026"},
  {"name": "Flygon", "art": "flygon", "released": "Apr 6, 2026"},
  {"name": "Regirock", "art": "regirock", "released": "Apr 20, 2026"},
  {"name": "Cottonee", "art": "cottonee", "released": "May 4, 2026"},
  {"name": "Whimsicott", "art": "whimsicott", "released": "May 4, 2026"},
  {"name": "Registeel", "art": "registeel", "released": "May 18, 2026"},
  {"name": "Combee", "art": "combee", "released": "May 25, 2026"},
  {"name": "Vespiquen", "art": "vespiquen", "released": "May 25, 2026"},
  {"name": "Electabuzz", "art": "electabuzz", "released": "Jun 8, 2026"},
  {"name": "Electivire", "art": "electivire", "released": "Jun 8, 2026"},
  {"name": "Hoothoot", "art": "hoothoot", "released": "Jun 22, 2026"},
  {"name": "Noctowl", "art": "noctowl", "released": "Jun 22, 2026"},
  {"name": "Deino", "art": "deino", "released": "Jul 13, 2026"},
  {"name": "Zweilous", "art": "zweilous", "released": "Jul 13, 2026"},
  {"name": "Hydreigon", "art": "hydreigon", "released": "Jul 13, 2026"},
  {"name": "Feebas", "art": "feebas", "released": "Jul 27, 2026"},
  {"name": "Milotic", "art": "milotic", "released": "Jul 27, 2026"},
  {"name": "Magmar", "art": "magmar", "released": "Aug 3, 2026"},
  {"name": "Magmortar", "art": "magmortar", "released": "Aug 3, 2026"},
  {"name": "Magikarp", "art": "magikarp", "released": "Aug 17, 2026"},
  {"name": "Gyarados", "art": "gyarados", "released": "Aug 17, 2026"},
  {"name": "Hitmontop", "art": "hitmontop", "released": "Aug 24, 2026"},
  {"name": "Rhyhorn", "art": "rhyhorn", "released": "Sep 14, 2026"},
  {"name": "Rhydon", "art": "rhydon", "released": "Sep 14, 2026"},
  {"name": "Rhyperior", "art": "rhyperior", "released": "Sep 14, 2026"}
];
