/**
 * All released Dynamax and Gigantamax Pokemon in Pokemon GO.
 *
 * GENERATED — do not hand-edit. Regenerate with: python3 scripts/update_dynamax.py
 * Sources: https://bulbapedia.bulbagarden.net/wiki/Dynamax_(GO)
 *          https://bulbapedia.bulbagarden.net/wiki/Gigantamax_(GO)
 *          PokeMiners game_master 8e227be44f28 (2026-08-29) — base stats, typing and move tables
 *
 * A Gigantamax form is tracked separately from its Dynamax entry — they are different
 * catches. hasGmax marks a Dynamax entry whose species also has a Gigantamax form.
 *
 * raid/stars is stored for Gigantamax only, where the battle is always a six-star
 * Gigantamax Max Battle (https://bulbapedia.bulbagarden.net/wiki/Max_Battle). The tier of a
 * plain Dynamax Pokemon belongs to the current Power Spot rotation rather than the species,
 * rotates weekly, and is deliberately NOT stored — it would be stale within days.
 *
 * rank   COMBAT POWER ONLY, on the same site-wide scale as web/mega-data.js: S/A/B/C/D by
 *        percentile of every fully evolved Pokemon and Mega in the game. A Gigantamax entry
 *        ranks on its species' stats — its G-Max move hits harder, but that damage is not in
 *        the Game Master and is not invented here.
 * role   Max Attacker / Guard / Spirit, when its stats put it in the top quarter of the
 *        roster for one. NOT part of the rank: Blissey is a D attacker and the best Max
 *        Spirit in the game, and that is the whole reason this field exists.
 * types  the species' own typing, from the Game Master
 * dps    sustained cycle DPS at level 40, 15/15/15, vs a neutral 200-defense target
 * moves  the moveset that DPS assumes; legacy marks one needing an Elite TM or a
 *        Community Day move
 */

const GIGANTAMAX = [
  {"name": "Venusaur", "art": "venusaur-gigantamax", "gmaxMove": "G-Max Vine Lash", "raid": "Gigantamax Battle", "stars": 6, "released": "October 26, 2024", "types": ["Grass", "Poison"], "dps": 12.1, "moves": "Vine Whip + Frenzy Plant", "legacy": true, "rank": "B", "role": "Guard"},
  {"name": "Charizard", "art": "charizard-gigantamax", "gmaxMove": "G-Max Wildfire", "raid": "Gigantamax Battle", "stars": 6, "released": "October 26, 2024", "types": ["Fire", "Flying"], "dps": 12.2, "moves": "Fire Spin + Blast Burn", "legacy": true, "rank": "B", "role": null},
  {"name": "Blastoise", "art": "blastoise-gigantamax", "gmaxMove": "G-Max Cannonade", "raid": "Gigantamax Battle", "stars": 6, "released": "October 26, 2024", "types": ["Water"], "dps": 10.0, "moves": "Water Gun + Hydro Cannon", "legacy": true, "rank": "D", "role": "Guard"},
  {"name": "Butterfree", "art": "butterfree-gigantamax", "gmaxMove": "G-Max Befuddle", "raid": "Gigantamax Battle", "stars": 6, "released": "August 3, 2025", "types": ["Bug", "Flying"], "dps": 8.5, "moves": "Bug Bite + Bug Buzz", "legacy": true, "rank": "D", "role": null},
  {"name": "Pikachu", "art": "pikachu-gigantamax", "gmaxMove": "G-Max Volt Crash", "raid": "Gigantamax Battle", "stars": 6, "released": "March 28, 2026", "types": ["Electric"], "dps": 6.8, "moves": "Thunder Shock + Wild Charge", "rank": "D", "role": null},
  {"name": "Meowth", "art": "meowth-gigantamax", "gmaxMove": "G-Max Gold Rush", "raid": "Gigantamax Battle", "stars": 6, "released": "February 15, 2026", "types": ["Normal"], "dps": 4.8, "moves": "Scratch + Foul Play", "rank": "D", "role": null},
  {"name": "Machamp", "art": "machamp-gigantamax", "gmaxMove": "G-Max Chi Strike", "raid": "Gigantamax Battle", "stars": 6, "released": "May 25, 2025", "types": ["Fighting"], "dps": 11.6, "moves": "Counter + Dynamic Punch", "rank": "C", "role": "Spirit"},
  {"name": "Gengar", "art": "gengar-gigantamax", "gmaxMove": "G-Max Terror", "raid": "Gigantamax Battle", "stars": 6, "released": "October 31, 2024", "types": ["Ghost", "Poison"], "dps": 13.6, "moves": "Lick + Shadow Ball", "legacy": true, "rank": "A", "role": "Attacker"},
  {"name": "Kingler", "art": "kingler-gigantamax", "gmaxMove": "G-Max Foam Burst", "raid": "Gigantamax Battle", "stars": 6, "released": "February 1, 2025", "types": ["Water"], "dps": 13.1, "moves": "Metal Claw + Crabhammer", "rank": "B", "role": "Attacker"},
  {"name": "Lapras", "art": "lapras-gigantamax", "gmaxMove": "G-Max Resonance", "raid": "Gigantamax Battle", "stars": 6, "released": "December 8, 2024", "types": ["Water", "Ice"], "dps": 8.9, "moves": "Water Gun + Blizzard", "rank": "D", "role": "Spirit"},
  {"name": "Snorlax", "art": "snorlax-gigantamax", "gmaxMove": "G-Max Replenish", "raid": "Gigantamax Battle", "stars": 6, "released": "April 19, 2025", "types": ["Normal"], "dps": 10.0, "moves": "Lick + Skull Bash", "rank": "D", "role": "Spirit"},
  {"name": "Garbodor", "art": "garbodor-gigantamax", "gmaxMove": "G-Max Malodor", "raid": "Gigantamax Battle", "stars": 6, "released": "November 1, 2025", "types": ["Poison"], "dps": 8.5, "moves": "Infestation + Gunk Shot", "rank": "D", "role": null},
  {"name": "Rillaboom", "art": "rillaboom-gigantamax", "gmaxMove": "G-Max Drum Solo", "raid": "Gigantamax Battle", "stars": 6, "released": "May 29, 2025", "types": ["Grass"], "dps": 12.6, "moves": "Scratch + Frenzy Plant", "legacy": true, "rank": "B", "role": "Spirit"},
  {"name": "Cinderace", "art": "cinderace-gigantamax", "gmaxMove": "G-Max Fireball", "raid": "Gigantamax Battle", "stars": 6, "released": "June 5, 2025", "types": ["Fire"], "dps": 13.3, "moves": "Fire Spin + Pyroball", "rank": "B", "role": "Attacker"},
  {"name": "Inteleon", "art": "inteleon-gigantamax", "gmaxMove": "G-Max Hydrosnipe", "raid": "Gigantamax Battle", "stars": 6, "released": "June 12, 2025", "types": ["Water"], "dps": 14.3, "moves": "Pound + Hydro Cannon", "legacy": true, "rank": "A", "role": "Attacker"},
  {"name": "Toxtricity", "art": "toxtricity-gigantamax", "gmaxMove": "G-Max Stun Shock", "raid": "Gigantamax Battle", "stars": 6, "released": "November 16, 2024", "types": ["Electric", "Poison"], "dps": 11.6, "moves": "Poison Jab + Wild Charge", "rank": "C", "role": null},
  {"name": "Grimmsnarl", "art": "grimmsnarl-gigantamax", "gmaxMove": "G-Max Snooze", "raid": "Gigantamax Battle", "stars": 6, "released": "November 7, 2025", "types": ["Dark", "Fairy"], "dps": 10.9, "moves": "Bite + Play Rough", "rank": "C", "role": "Spirit"}
];

const DYNAMAX = [
  {"name": "Wooloo", "art": "wooloo", "released": "Sep 4, 2024", "types": ["Normal"], "dps": 4.9, "moves": "Tackle + Wild Charge", "rank": "D", "role": null},
  {"name": "Dubwool", "art": "dubwool", "released": "Sep 4, 2024", "types": ["Normal"], "dps": 8.1, "moves": "Tackle + Wild Charge", "rank": "D", "role": "Guard"},
  {"name": "Skwovet", "art": "skwovet", "released": "Sep 4, 2024", "types": ["Normal"], "dps": 5.1, "moves": "Tackle + Body Slam", "rank": "D", "role": null},
  {"name": "Greedent", "art": "greedent", "released": "Sep 4, 2024", "types": ["Normal"], "dps": 7.6, "moves": "Tackle + Body Slam", "rank": "D", "role": "Spirit"},
  {"name": "Bulbasaur", "art": "bulbasaur", "released": "Sep 10, 2024", "types": ["Grass", "Poison"], "dps": 6.5, "moves": "Vine Whip + Power Whip", "rank": "D", "role": null},
  {"name": "Ivysaur", "art": "ivysaur", "released": "Sep 10, 2024", "types": ["Grass", "Poison"], "dps": 8.8, "moves": "Vine Whip + Power Whip", "rank": "D", "role": null},
  {"name": "Venusaur", "art": "venusaur", "released": "Sep 10, 2024", "hasGmax": true, "types": ["Grass", "Poison"], "dps": 12.1, "moves": "Vine Whip + Frenzy Plant", "legacy": true, "rank": "B", "role": "Guard"},
  {"name": "Charmander", "art": "charmander", "released": "Sep 10, 2024", "types": ["Fire"], "dps": 5.9, "moves": "Ember + Flamethrower", "rank": "D", "role": null},
  {"name": "Charmeleon", "art": "charmeleon", "released": "Sep 10, 2024", "types": ["Fire"], "dps": 7.9, "moves": "Fire Fang + Flamethrower", "rank": "D", "role": null},
  {"name": "Charizard", "art": "charizard", "released": "Sep 10, 2024", "hasGmax": true, "types": ["Fire", "Flying"], "dps": 12.2, "moves": "Fire Spin + Blast Burn", "legacy": true, "rank": "B", "role": null},
  {"name": "Squirtle", "art": "squirtle", "released": "Sep 10, 2024", "types": ["Water"], "dps": 4.9, "moves": "Tackle + Aqua Tail", "rank": "D", "role": null},
  {"name": "Wartortle", "art": "wartortle", "released": "Sep 10, 2024", "types": ["Water"], "dps": 6.4, "moves": "Water Gun + Hydro Pump", "rank": "D", "role": null},
  {"name": "Blastoise", "art": "blastoise", "released": "Sep 10, 2024", "hasGmax": true, "types": ["Water"], "dps": 10.0, "moves": "Water Gun + Hydro Cannon", "legacy": true, "rank": "D", "role": "Guard"},
  {"name": "Beldum", "art": "beldum", "released": "Sep 18, 2024", "types": ["Steel", "Psychic"], "dps": 3.3, "moves": "Take Down + Iron Head", "rank": "D", "role": null},
  {"name": "Metang", "art": "metang", "released": "Sep 18, 2024", "types": ["Steel", "Psychic"], "dps": 8.1, "moves": "Metal Claw + Psychic", "rank": "D", "role": null},
  {"name": "Metagross", "art": "metagross", "released": "Sep 18, 2024", "types": ["Steel", "Psychic"], "dps": 14.3, "moves": "Fury Cutter + Meteor Mash", "legacy": true, "rank": "A", "role": "Attacker"},
  {"name": "Grookey", "art": "grookey", "released": "Oct 1, 2024", "types": ["Grass"], "dps": 6.7, "moves": "Razor Leaf + Grass Knot", "rank": "D", "role": null},
  {"name": "Thwackey", "art": "thwackey", "released": "Oct 1, 2024", "types": ["Grass"], "dps": 8.7, "moves": "Scratch + Grass Knot", "rank": "D", "role": null},
  {"name": "Rillaboom", "art": "rillaboom", "released": "Oct 1, 2024", "hasGmax": true, "types": ["Grass"], "dps": 12.6, "moves": "Scratch + Frenzy Plant", "legacy": true, "rank": "B", "role": "Spirit"},
  {"name": "Scorbunny", "art": "scorbunny", "released": "Oct 1, 2024", "types": ["Fire"], "dps": 6.6, "moves": "Fire Spin + Flamethrower", "rank": "D", "role": null},
  {"name": "Raboot", "art": "raboot", "released": "Oct 1, 2024", "types": ["Fire"], "dps": 8.1, "moves": "Fire Spin + Flamethrower", "rank": "D", "role": null},
  {"name": "Cinderace", "art": "cinderace", "released": "Oct 1, 2024", "hasGmax": true, "types": ["Fire"], "dps": 13.3, "moves": "Fire Spin + Pyroball", "rank": "B", "role": "Attacker"},
  {"name": "Sobble", "art": "sobble", "released": "Oct 1, 2024", "types": ["Water"], "dps": 6.3, "moves": "Pound + Surf", "rank": "D", "role": null},
  {"name": "Drizzile", "art": "drizzile", "released": "Oct 1, 2024", "types": ["Water"], "dps": 9.1, "moves": "Pound + Surf", "rank": "D", "role": null},
  {"name": "Inteleon", "art": "inteleon", "released": "Oct 1, 2024", "hasGmax": true, "types": ["Water"], "dps": 14.3, "moves": "Pound + Hydro Cannon", "legacy": true, "rank": "A", "role": "Attacker"},
  {"name": "Falinks", "art": "falinks", "released": "Oct 1, 2024", "types": ["Fighting"], "dps": 9.3, "moves": "Counter + Super Power", "rank": "D", "role": null},
  {"name": "Gastly", "art": "gastly", "released": "Oct 22, 2024", "types": ["Ghost", "Poison"], "dps": 9.7, "moves": "Lick + Sludge Bomb", "rank": "D", "role": null},
  {"name": "Haunter", "art": "haunter", "released": "Oct 22, 2024", "types": ["Ghost", "Poison"], "dps": 11.5, "moves": "Shadow Claw + Shadow Ball", "rank": "C", "role": null},
  {"name": "Gengar", "art": "gengar", "released": "Oct 22, 2024", "hasGmax": true, "types": ["Ghost", "Poison"], "dps": 13.6, "moves": "Lick + Shadow Ball", "legacy": true, "rank": "A", "role": "Attacker"},
  {"name": "Drilbur", "art": "drilbur", "released": "Nov 15, 2024", "types": ["Ground"], "dps": 7.8, "moves": "Scratch + Drill Run", "rank": "D", "role": null},
  {"name": "Excadrill", "art": "excadrill", "released": "Nov 15, 2024", "types": ["Ground", "Steel"], "dps": 12.6, "moves": "Metal Claw + Earthquake", "rank": "B", "role": "Attacker"},
  {"name": "Toxtricity", "art": "toxtricity-amped", "released": "Nov 16, 2024", "form": "Amped Form", "hasGmax": true, "types": ["Electric", "Poison"], "dps": 11.6, "moves": "Poison Jab + Wild Charge", "rank": "C", "role": null},
  {"name": "Toxtricity", "art": "toxtricity-low-key", "released": "Nov 16, 2024", "form": "Low Key Form", "hasGmax": true, "types": ["Electric", "Poison"], "dps": 11.6, "moves": "Poison Jab + Wild Charge", "rank": "C", "role": null},
  {"name": "Machop", "art": "machop", "released": "Dec 3, 2024", "types": ["Fighting"], "dps": 6.4, "moves": "Karate Chop + Cross Chop", "rank": "D", "role": null},
  {"name": "Machoke", "art": "machoke", "released": "Dec 3, 2024", "types": ["Fighting"], "dps": 9.2, "moves": "Low Kick + Dynamic Punch", "rank": "D", "role": null},
  {"name": "Machamp", "art": "machamp", "released": "Dec 3, 2024", "hasGmax": true, "types": ["Fighting"], "dps": 11.6, "moves": "Counter + Dynamic Punch", "rank": "C", "role": "Spirit"},
  {"name": "Krabby", "art": "krabby", "released": "Dec 9, 2024", "types": ["Water"], "dps": 9.1, "moves": "Bubble + Razor Shell", "rank": "D", "role": null},
  {"name": "Kingler", "art": "kingler", "released": "Dec 9, 2024", "hasGmax": true, "types": ["Water"], "dps": 13.1, "moves": "Metal Claw + Crabhammer", "rank": "B", "role": "Attacker"},
  {"name": "Cryogonal", "art": "cryogonal", "released": "Dec 23, 2024", "types": ["Ice"], "dps": 9.0, "moves": "Frost Breath + Triple Axel", "rank": "D", "role": "Guard"},
  {"name": "Articuno", "art": "articuno", "released": "Jan 20, 2025", "types": ["Ice", "Flying"], "dps": 9.1, "moves": "Frost Breath + Blizzard", "rank": "D", "role": "Guard"},
  {"name": "Zapdos", "art": "zapdos", "released": "Jan 27, 2025", "types": ["Electric", "Flying"], "dps": 12.2, "moves": "Thunder Shock + Zap Cannon", "legacy": true, "rank": "B", "role": "Attacker"},
  {"name": "Moltres", "art": "moltres", "released": "Feb 3, 2025", "types": ["Fire", "Flying"], "dps": 13.9, "moves": "Fire Spin + Fly", "rank": "A", "role": "Attacker"},
  {"name": "Pidove", "art": "pidove", "released": "Feb 17, 2025", "types": ["Normal", "Flying"], "dps": 4.7, "moves": "Air Slash + Aerial Ace", "rank": "D", "role": null},
  {"name": "Tranquill", "art": "tranquill", "released": "Feb 17, 2025", "types": ["Normal", "Flying"], "dps": 7.3, "moves": "Air Slash + Sky Attack", "rank": "D", "role": null},
  {"name": "Unfezant", "art": "unfezant", "released": "Feb 17, 2025", "types": ["Normal", "Flying"], "dps": 10.6, "moves": "Air Slash + Sky Attack", "rank": "C", "role": null},
  {"name": "Darumaka", "art": "darumaka", "released": "Feb 24, 2025", "types": ["Fire"], "dps": 7.3, "moves": "Fire Fang + Fire Punch", "rank": "D", "role": null},
  {"name": "Darmanitan", "art": "darmanitan", "released": "Feb 24, 2025", "types": ["Fire"], "dps": 13.4, "moves": "Fire Fang + Overheat", "rank": "B", "role": "Attacker"},
  {"name": "Kubfu", "art": "kubfu", "released": "Mar 5, 2025", "types": ["Fighting"], "dps": 8.7, "moves": "Counter + Dynamic Punch", "rank": "D", "role": null},
  {"name": "Raikou", "art": "raikou", "released": "Mar 15, 2025", "types": ["Electric"], "dps": 12.5, "moves": "Thunder Shock + Aura Sphere", "rank": "B", "role": "Attacker"},
  {"name": "Chansey", "art": "chansey", "released": "Mar 17, 2025", "types": ["Normal"], "dps": 4.8, "moves": "Pound + Hyper Beam", "rank": "D", "role": "Spirit"},
  {"name": "Blissey", "art": "blissey", "released": "Mar 17, 2025", "types": ["Normal"], "dps": 8.0, "moves": "Pound + Hyper Beam", "rank": "D", "role": "Spirit"},
  {"name": "Caterpie", "art": "caterpie", "released": "Mar 24, 2025", "types": ["Bug"], "rank": "D", "role": null},
  {"name": "Metapod", "art": "metapod", "released": "Mar 24, 2025", "types": ["Bug"], "rank": "D", "role": null},
  {"name": "Butterfree", "art": "butterfree", "released": "Mar 24, 2025", "hasGmax": true, "types": ["Bug", "Flying"], "dps": 8.5, "moves": "Bug Bite + Bug Buzz", "legacy": true, "rank": "D", "role": null},
  {"name": "Passimian", "art": "passimian", "released": "Apr 7, 2025", "types": ["Fighting"], "dps": 10.7, "moves": "Counter + Close Combat", "rank": "C", "role": "Spirit"},
  {"name": "Entei", "art": "entei", "released": "Apr 26, 2025", "types": ["Fire"], "dps": 11.9, "moves": "Fire Spin + Overheat", "rank": "C", "role": "Spirit"},
  {"name": "Suicune", "art": "suicune", "released": "May 10, 2025", "types": ["Water"], "dps": 9.1, "moves": "Water Gun + Hydro Pump", "rank": "D", "role": "Guard"},
  {"name": "Sableye", "art": "sableye", "released": "May 19, 2025", "types": ["Dark", "Ghost"], "dps": 7.6, "moves": "Shadow Claw + Foul Play", "rank": "D", "role": null},
  {"name": "Urshifu", "art": "urshifu-single-strike", "released": "May 21, 2025", "form": "Single Strike Style", "types": ["Fighting"], "dps": 12.8, "moves": "Counter + Dynamic Punch", "rank": "B", "role": "Attacker"},
  {"name": "Urshifu", "art": "urshifu-rapid-strike", "released": "May 21, 2025", "form": "Rapid Strike Style", "types": ["Fighting"], "dps": 12.8, "moves": "Counter + Dynamic Punch", "rank": "B", "role": "Attacker"},
  {"name": "Rookidee", "art": "rookidee", "released": "May 26, 2025", "types": ["Flying"], "dps": 5.0, "moves": "Peck + Sky Attack", "rank": "D", "role": null},
  {"name": "Corvisquire", "art": "corvisquire", "released": "May 26, 2025", "types": ["Flying"], "dps": 7.3, "moves": "Sand Attack + Sky Attack", "rank": "D", "role": null},
  {"name": "Corviknight", "art": "corviknight", "released": "May 26, 2025", "types": ["Flying", "Steel"], "dps": 8.4, "moves": "Steel Wing + Sky Attack", "rank": "D", "role": "Spirit"},
  {"name": "Hatenna", "art": "hatenna", "released": "Jun 16, 2025", "types": ["Psychic"], "dps": 5.6, "moves": "Confusion + Psychic", "rank": "D", "role": null},
  {"name": "Hattrem", "art": "hattrem", "released": "Jun 16, 2025", "types": ["Psychic"], "dps": 7.8, "moves": "Confusion + Psychic", "rank": "D", "role": null},
  {"name": "Hatterene", "art": "hatterene", "released": "Jun 16, 2025", "types": ["Psychic", "Fairy"], "dps": 11.7, "moves": "Confusion + Psychic", "rank": "C", "role": "Attacker"},
  {"name": "Shuckle", "art": "shuckle", "released": "Jun 30, 2025", "types": ["Bug", "Rock"], "dps": 1.7, "moves": "Struggle Bug + Stone Edge", "rank": "D", "role": "Guard"},
  {"name": "Wailmer", "art": "wailmer", "released": "Jul 14, 2025", "types": ["Water"], "dps": 5.9, "moves": "Water Gun + Heavy Slam", "rank": "D", "role": "Spirit"},
  {"name": "Wailord", "art": "wailord", "released": "Jul 14, 2025", "types": ["Water"], "dps": 8.9, "moves": "Water Gun + Surf", "rank": "D", "role": "Spirit"},
  {"name": "Latias", "art": "latias", "released": "Jul 26, 2025", "types": ["Dragon", "Psychic"], "dps": 11.9, "moves": "Dragon Breath + Aura Sphere", "rank": "C", "role": "Guard"},
  {"name": "Latios", "art": "latios", "released": "Jul 26, 2025", "types": ["Dragon", "Psychic"], "dps": 14.2, "moves": "Dragon Breath + Aura Sphere", "rank": "A", "role": "Attacker"},
  {"name": "Kabuto", "art": "kabuto", "released": "Jul 28, 2025", "types": ["Rock", "Water"], "dps": 6.2, "moves": "Mud Shot + Ancient Power", "rank": "D", "role": null},
  {"name": "Kabutops", "art": "kabutops", "released": "Jul 28, 2025", "types": ["Rock", "Water"], "dps": 10.2, "moves": "Waterfall + Stone Edge", "rank": "C", "role": "Guard"},
  {"name": "Omanyte", "art": "omanyte", "released": "Aug 4, 2025", "types": ["Rock", "Water"], "dps": 7.6, "moves": "Water Gun + Rock Blast", "rank": "D", "role": null},
  {"name": "Omastar", "art": "omastar", "released": "Aug 4, 2025", "types": ["Rock", "Water"], "dps": 9.9, "moves": "Rock Throw + Hydro Pump", "legacy": true, "rank": "D", "role": "Guard"},
  {"name": "Trubbish", "art": "trubbish", "released": "Aug 11, 2025", "types": ["Poison"], "dps": 5.8, "moves": "Pound + Gunk Shot", "rank": "D", "role": null},
  {"name": "Garbodor", "art": "garbodor", "released": "Aug 11, 2025", "hasGmax": true, "types": ["Poison"], "dps": 8.5, "moves": "Infestation + Gunk Shot", "rank": "D", "role": null},
  {"name": "Abra", "art": "abra", "released": "Sep 15, 2025", "types": ["Psychic"], "dps": 8.7, "moves": "Zen Headbutt + Shadow Ball", "rank": "D", "role": null},
  {"name": "Kadabra", "art": "kadabra", "released": "Sep 15, 2025", "types": ["Psychic"], "dps": 10.8, "moves": "Confusion + Shadow Ball", "rank": "C", "role": "Attacker"},
  {"name": "Alakazam", "art": "alakazam", "released": "Sep 15, 2025", "types": ["Psychic"], "dps": 13.0, "moves": "Confusion + Psychic", "legacy": true, "rank": "B", "role": "Attacker"},
  {"name": "Duraludon", "art": "duraludon", "released": "Sep 30, 2025", "types": ["Steel", "Dragon"], "dps": 11.5, "moves": "Dragon Tail + Flash Cannon", "rank": "C", "role": "Attacker"},
  {"name": "Bounsweet", "art": "bounsweet", "released": "Oct 13, 2025", "types": ["Grass"], "dps": 3.2, "moves": "Razor Leaf + Energy Ball", "rank": "D", "role": null},
  {"name": "Steenee", "art": "steenee", "released": "Oct 13, 2025", "types": ["Grass"], "dps": 4.2, "moves": "Razor Leaf + Grass Knot", "rank": "D", "role": null},
  {"name": "Tsareena", "art": "tsareena", "released": "Oct 13, 2025", "types": ["Grass"], "dps": 11.6, "moves": "Magical Leaf + Grass Knot", "rank": "C", "role": "Guard"},
  {"name": "Woobat", "art": "woobat", "released": "Oct 27, 2025", "types": ["Psychic", "Flying"], "dps": 5.1, "moves": "Confusion + Psyshock", "rank": "D", "role": null},
  {"name": "Swoobat", "art": "swoobat", "released": "Oct 27, 2025", "types": ["Psychic", "Flying"], "dps": 8.9, "moves": "Air Slash + Fly", "rank": "D", "role": null},
  {"name": "Inkay", "art": "inkay", "released": "Nov 3, 2025", "types": ["Dark", "Psychic"], "dps": 5.1, "moves": "Psywave + Night Slash", "rank": "D", "role": null},
  {"name": "Malamar", "art": "malamar", "released": "Nov 3, 2025", "types": ["Dark", "Psychic"], "dps": 8.0, "moves": "Psycho Cut + Foul Play", "rank": "D", "role": "Spirit"},
  {"name": "Ralts", "art": "ralts", "released": "Nov 10, 2025", "types": ["Psychic", "Fairy"], "dps": 4.1, "moves": "Confusion + Psyshock", "rank": "D", "role": null},
  {"name": "Kirlia", "art": "kirlia", "released": "Nov 10, 2025", "types": ["Psychic", "Fairy"], "dps": 6.0, "moves": "Confusion + Psychic", "rank": "D", "role": null},
  {"name": "Gardevoir", "art": "gardevoir", "released": "Nov 10, 2025", "types": ["Psychic", "Fairy"], "dps": 11.7, "moves": "Confusion + Psychic", "rank": "C", "role": "Guard"},
  {"name": "Gallade", "art": "gallade", "released": "Nov 10, 2025", "types": ["Psychic", "Fighting"], "dps": 11.7, "moves": "Confusion + Psychic", "rank": "C", "role": "Guard"},
  {"name": "Eevee", "art": "eevee", "released": "Nov 24, 2025", "types": ["Normal"], "dps": 5.8, "moves": "Tackle + Last Resort", "legacy": true, "rank": "D", "role": null},
  {"name": "Vaporeon", "art": "vaporeon", "released": "Nov 24, 2025", "types": ["Water"], "dps": 9.7, "moves": "Water Gun + Hydro Pump", "rank": "D", "role": "Spirit"},
  {"name": "Jolteon", "art": "jolteon", "released": "Nov 24, 2025", "types": ["Electric"], "dps": 11.5, "moves": "Thunder Shock + Zap Cannon", "legacy": true, "rank": "C", "role": "Attacker"},
  {"name": "Flareon", "art": "flareon", "released": "Nov 24, 2025", "types": ["Fire"], "dps": 13.0, "moves": "Fire Spin + Overheat", "rank": "B", "role": "Attacker"},
  {"name": "Espeon", "art": "espeon", "released": "Nov 24, 2025", "types": ["Psychic"], "dps": 12.8, "moves": "Confusion + Psychic", "rank": "B", "role": "Attacker"},
  {"name": "Umbreon", "art": "umbreon", "released": "Nov 24, 2025", "types": ["Dark"], "dps": 6.7, "moves": "Snarl + Foul Play", "rank": "D", "role": "Guard"},
  {"name": "Leafeon", "art": "leafeon", "released": "Nov 24, 2025", "types": ["Grass"], "dps": 10.9, "moves": "Razor Leaf + Solar Beam", "rank": "C", "role": "Guard"},
  {"name": "Glaceon", "art": "glaceon", "released": "Nov 24, 2025", "types": ["Ice"], "dps": 10.9, "moves": "Frost Breath + Avalanche", "rank": "C", "role": "Guard"},
  {"name": "Sylveon", "art": "sylveon", "released": "Nov 24, 2025", "types": ["Fairy"], "dps": 9.7, "moves": "Charm + Dazzling Gleam", "rank": "D", "role": "Guard"},
  {"name": "Lugia", "art": "lugia", "released": "Nov 29, 2025", "types": ["Psychic", "Flying"], "dps": 11.0, "moves": "Extrasensory + Aeroblast", "legacy": true, "rank": "C", "role": "Guard"},
  {"name": "Hitmonlee", "art": "hitmonlee", "released": "Dec 11, 2025", "types": ["Fighting"], "dps": 10.3, "moves": "Double Kick + Close Combat", "rank": "C", "role": null},
  {"name": "Hitmonchan", "art": "hitmonchan", "released": "Dec 11, 2025", "types": ["Fighting"], "dps": 9.4, "moves": "Counter + Close Combat", "rank": "D", "role": "Guard"},
  {"name": "Spheal", "art": "spheal", "released": "Dec 22, 2025", "types": ["Ice", "Water"], "dps": 4.8, "moves": "Water Gun + Aurora Beam", "rank": "D", "role": null},
  {"name": "Sealeo", "art": "sealeo", "released": "Dec 22, 2025", "types": ["Ice", "Water"], "dps": 6.5, "moves": "Water Gun + Surf", "rank": "D", "role": "Spirit"},
  {"name": "Walrein", "art": "walrein", "released": "Dec 22, 2025", "types": ["Ice", "Water"], "dps": 9.2, "moves": "Waterfall + Blizzard", "rank": "D", "role": "Spirit"},
  {"name": "Drampa", "art": "drampa", "released": "Jan 5, 2026", "types": ["Normal", "Dragon"], "dps": 11.3, "moves": "Dragon Breath + Fly", "rank": "C", "role": "Attacker"},
  {"name": "Roggenrola", "art": "roggenrola", "released": "Jan 26, 2026", "types": ["Rock"], "dps": 6.2, "moves": "Smack Down + Stone Edge", "rank": "D", "role": null},
  {"name": "Boldore", "art": "boldore", "released": "Jan 26, 2026", "types": ["Rock"], "dps": 7.9, "moves": "Smack Down + Stone Edge", "rank": "D", "role": null},
  {"name": "Gigalith", "art": "gigalith", "released": "Jan 26, 2026", "types": ["Rock"], "dps": 12.9, "moves": "Lock On + Meteor Beam", "legacy": true, "rank": "B", "role": "Guard"},
  {"name": "Ho-Oh", "art": "ho-oh", "released": "Jan 31, 2026", "types": ["Fire", "Flying"], "dps": 12.3, "moves": "Incinerate + Brave Bird", "rank": "B", "role": "Guard"},
  {"name": "Growlithe", "art": "growlithe", "released": "Feb 9, 2026", "types": ["Fire"], "dps": 6.3, "moves": "Ember + Flamethrower", "rank": "D", "role": null},
  {"name": "Arcanine", "art": "arcanine", "released": "Feb 9, 2026", "types": ["Fire"], "dps": 11.1, "moves": "Fire Fang + Fire Blast", "rank": "C", "role": "Spirit"},
  {"name": "Pikachu", "art": "pikachu", "released": "Mar 9, 2026", "hasGmax": true, "types": ["Electric"], "dps": 6.8, "moves": "Thunder Shock + Wild Charge", "rank": "D", "role": null},
  {"name": "Raichu", "art": "raichu", "released": "Mar 9, 2026", "types": ["Electric"], "dps": 9.4, "moves": "Volt Switch + Wild Charge", "rank": "D", "role": null},
  {"name": "Regice", "art": "regice", "released": "Mar 23, 2026", "types": ["Ice"], "dps": 8.8, "moves": "Frost Breath + Blizzard", "rank": "D", "role": "Guard"},
  {"name": "Trapinch", "art": "trapinch", "released": "Apr 6, 2026", "types": ["Ground"], "dps": 7.7, "moves": "Sand Attack + Scorching Sands", "rank": "D", "role": null},
  {"name": "Vibrava", "art": "vibrava", "released": "Apr 6, 2026", "types": ["Ground", "Dragon"], "dps": 7.5, "moves": "Dragon Breath + Scorching Sands", "rank": "D", "role": null},
  {"name": "Flygon", "art": "flygon", "released": "Apr 6, 2026", "types": ["Ground", "Dragon"], "dps": 11.1, "moves": "Sand Attack + Boomburst", "rank": "C", "role": null},
  {"name": "Regirock", "art": "regirock", "released": "Apr 20, 2026", "types": ["Rock"], "dps": 8.2, "moves": "Rock Throw + Stone Edge", "rank": "D", "role": "Guard"},
  {"name": "Cottonee", "art": "cottonee", "released": "May 4, 2026", "types": ["Grass", "Fairy"], "dps": 4.4, "moves": "Charm + Grass Knot", "rank": "D", "role": null},
  {"name": "Whimsicott", "art": "whimsicott", "released": "May 4, 2026", "types": ["Grass", "Fairy"], "dps": 8.5, "moves": "Fairy Wind + Grass Knot", "rank": "D", "role": null},
  {"name": "Registeel", "art": "registeel", "released": "May 18, 2026", "types": ["Steel"], "dps": 7.8, "moves": "Metal Claw + Flash Cannon", "rank": "D", "role": "Guard"},
  {"name": "Combee", "art": "combee", "released": "May 25, 2026", "types": ["Bug", "Flying"], "dps": 3.2, "moves": "Bug Bite + Bug Buzz", "rank": "D", "role": null},
  {"name": "Vespiquen", "art": "vespiquen", "released": "May 25, 2026", "types": ["Bug", "Flying"], "dps": 7.3, "moves": "Fury Cutter + Bug Buzz", "rank": "D", "role": "Guard"},
  {"name": "Electabuzz", "art": "electabuzz", "released": "Jun 8, 2026", "types": ["Electric"], "dps": 10.0, "moves": "Thunder Shock + Thunderbolt", "rank": "D", "role": null},
  {"name": "Electivire", "art": "electivire", "released": "Jun 8, 2026", "types": ["Electric"], "dps": 12.5, "moves": "Thunder Shock + Wild Charge", "rank": "B", "role": "Attacker"},
  {"name": "Hoothoot", "art": "hoothoot", "released": "Jun 22, 2026", "types": ["Normal", "Flying"], "dps": 3.7, "moves": "Feint Attack + Sky Attack", "rank": "D", "role": null},
  {"name": "Noctowl", "art": "noctowl", "released": "Jun 22, 2026", "types": ["Normal", "Flying"], "dps": 7.3, "moves": "Wing Attack + Sky Attack", "rank": "D", "role": "Spirit"},
  {"name": "Deino", "art": "deino", "released": "Jul 13, 2026", "types": ["Dark", "Dragon"], "dps": 5.6, "moves": "Tackle + Dragon Pulse", "rank": "D", "role": null},
  {"name": "Zweilous", "art": "zweilous", "released": "Jul 13, 2026", "types": ["Dark", "Dragon"], "dps": 7.7, "moves": "Bite + Dragon Pulse", "rank": "D", "role": null},
  {"name": "Hydreigon", "art": "hydreigon", "released": "Jul 13, 2026", "types": ["Dark", "Dragon"], "dps": 12.0, "moves": "Bite + Brutal Swing", "legacy": true, "rank": "C", "role": "Attacker"},
  {"name": "Feebas", "art": "feebas", "released": "Jul 27, 2026", "types": ["Water"], "dps": 2.1, "moves": "Tackle + Mirror Coat", "rank": "D", "role": null},
  {"name": "Milotic", "art": "milotic", "released": "Jul 27, 2026", "types": ["Water"], "dps": 9.1, "moves": "Waterfall + Surf", "rank": "D", "role": "Guard"},
  {"name": "Magmar", "art": "magmar", "released": "Aug 3, 2026", "types": ["Fire"], "dps": 9.6, "moves": "Ember + Fire Blast", "rank": "D", "role": null},
  {"name": "Magmortar", "art": "magmortar", "released": "Aug 3, 2026", "types": ["Fire"], "dps": 12.2, "moves": "Fire Spin + Fire Blast", "rank": "B", "role": "Attacker"},
  {"name": "Magikarp", "art": "magikarp", "released": "Aug 17, 2026", "types": ["Water"], "rank": "D", "role": null},
  {"name": "Gyarados", "art": "gyarados", "released": "Aug 17, 2026", "types": ["Water", "Flying"], "dps": 10.9, "moves": "Waterfall + Hydro Pump", "rank": "C", "role": "Spirit"},
  {"name": "Hitmontop", "art": "hitmontop", "released": "Aug 24, 2026", "types": ["Fighting"], "dps": 8.2, "moves": "Counter + Close Combat", "rank": "D", "role": "Guard"},
  {"name": "Rhyhorn", "art": "rhyhorn", "released": "Sep 14, 2026", "types": ["Ground", "Rock"], "dps": 6.1, "moves": "Mud Slap + Bulldoze", "rank": "D", "role": null},
  {"name": "Rhydon", "art": "rhydon", "released": "Sep 14, 2026", "types": ["Ground", "Rock"], "dps": 10.8, "moves": "Mud Slap + Earthquake", "rank": "C", "role": "Spirit"},
  {"name": "Rhyperior", "art": "rhyperior", "released": "Sep 14, 2026", "types": ["Ground", "Rock"], "dps": 12.1, "moves": "Mud Slap + Rock Wrecker", "legacy": true, "rank": "B", "role": "Spirit"}
];
