/**
 * All released Mega Evolutions and Primal Reversions in Pokemon GO.
 *
 * GENERATED — do not hand-edit. Regenerate with: python3 scripts/update_megas.py
 * Source: https://bulbapedia.bulbagarden.net/wiki/Mega_Evolution_(GO)
 *         PokeMiners game_master 8e227be44f28 (2026-08-29) — stats, moves and the Mega boost multipliers
 * Unreleased (HTML-commented) rows are excluded.
 *
 * energy  first-time activation cost; later activations cost far less
 * raid    battle class for this species: Mega Raid (4 stars), Legendary Mega Raid (6) or
 *         Primal Raid (5). Derived from the rule stated on
 *         https://bulbapedia.bulbagarden.net/wiki/Raid_Battle_(GO) plus Bulbapedia's
 *         Legendary and Mythical categories. It is NOT a claim that the Pokemon is in the
 *         raid rotation right now — that rotates and is deliberately not stored.
 *         Super Mega Raid is an event-driven variant, so it is not derived per species.
 * boosts  party-wide type bonus; weather-based (not own typing) when weatherBoost is set
 * attack  extra Charged Attack unlocked at Super Max Mega Level
 * rank    COMBAT POWER ONLY. S/A/B/C/D by percentile of every fully evolved Pokemon and
 *         Mega in the game — S is the top 5%, D is below the median. It says nothing about
 *         Mega Energy cost or type coverage. "?" means the Game Master has no entry yet.
 *         See scripts/rank.py for the damage model and the bands.
 * dps     sustained cycle DPS at level 40, 15/15/15, vs a neutral 200-defense target
 * moves   the moveset that DPS assumes; legacy marks one needing an Elite TM or a
 *         Community Day move, so the rank is unreachable without it
 * isNew   GO-original Mega with no mainline artwork; artFallback is base-species art
 */

const MEGAS = [
  {"name": "Mega Venusaur", "art": "venusaur-mega", "types": ["Grass", "Poison"], "boosts": ["Grass", "Poison"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "August 27, 2020", "dps": 13.5, "moves": "Vine Whip + Frenzy Plant", "legacy": true, "rank": "B"},
  {"name": "Mega Charizard X", "art": "charizard-mega-x", "types": ["Fire", "Dragon"], "boosts": ["Fire", "Dragon"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "August 27, 2020", "dps": 14.7, "moves": "Dragon Breath + Blast Burn", "legacy": true, "rank": "A"},
  {"name": "Mega Charizard Y", "art": "charizard-mega-y", "types": ["Fire", "Flying"], "boosts": ["Fire", "Flying"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "August 27, 2020", "dps": 17.1, "moves": "Fire Spin + Blast Burn", "legacy": true, "rank": "S"},
  {"name": "Mega Blastoise", "art": "blastoise-mega", "types": ["Water"], "boosts": ["Water"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "August 27, 2020", "dps": 14.3, "moves": "Water Gun + Hydro Cannon", "legacy": true, "rank": "A"},
  {"name": "Mega Beedrill", "art": "beedrill-mega", "types": ["Bug", "Poison"], "boosts": ["Bug", "Poison"], "energy": 100, "raid": "Mega Raid", "stars": 4, "released": "August 27, 2020", "dps": 14.7, "moves": "Poison Jab + Sludge Bomb", "attack": "Fell Stinger+", "rank": "A"},
  {"name": "Mega Pidgeot", "art": "pidgeot-mega", "types": ["Normal", "Flying"], "boosts": ["Normal", "Flying"], "energy": 100, "raid": "Mega Raid", "stars": 4, "released": "September 18, 2020", "dps": 15.1, "moves": "Gust + Brave Bird", "legacy": true, "rank": "A"},
  {"name": "Mega Raichu X", "art": "raichu-mega-x", "types": ["Electric"], "boosts": ["Electric"], "energy": 300, "raid": "Mega Raid", "stars": 4, "released": "July 18, 2026", "dps": 13.4, "moves": "Thunder Shock + Wild Charge", "artFallback": "raichu", "isNew": true, "attack": "Volt Tackle+", "rank": "B"},
  {"name": "Mega Raichu Y", "art": "raichu-mega-y", "types": ["Electric"], "boosts": ["Electric"], "energy": 300, "raid": "Mega Raid", "stars": 4, "released": "July 18, 2026", "dps": 16.6, "moves": "Thunder Shock + Wild Charge", "artFallback": "raichu", "isNew": true, "attack": "Zap Cannon+", "rank": "S"},
  {"name": "Mega Alakazam", "art": "alakazam-mega", "types": ["Psychic"], "boosts": ["Psychic"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "September 12, 2022", "dps": 17.7, "moves": "Confusion + Psychic", "legacy": true, "rank": "S"},
  {"name": "Mega Victreebel", "art": "victreebel-mega", "types": ["Grass", "Poison"], "boosts": ["Grass", "Poison"], "energy": 300, "raid": "Mega Raid", "stars": 4, "released": "February 20, 2026", "dps": 13.7, "moves": "Magical Leaf + Solar Beam", "legacy": true, "artFallback": "victreebel", "isNew": true, "attack": "Acid Spray+", "rank": "A"},
  {"name": "Mega Slowbro", "art": "slowbro-mega", "types": ["Water", "Psychic"], "boosts": ["Water", "Psychic"], "energy": 100, "raid": "Mega Raid", "stars": 4, "released": "June 8, 2021", "dps": 10.9, "moves": "Confusion + Psychic", "rank": "C"},
  {"name": "Mega Gengar", "art": "gengar-mega", "types": ["Ghost", "Poison"], "boosts": ["Ghost", "Poison"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "October 23, 2020", "dps": 17.6, "moves": "Lick + Shadow Ball", "legacy": true, "rank": "S"},
  {"name": "Mega Kangaskhan", "art": "kangaskhan-mega", "types": ["Normal"], "boosts": ["Normal"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "April 29, 2022", "dps": 9.9, "moves": "Mud Slap + Earthquake", "rank": "D"},
  {"name": "Mega Starmie", "art": "starmie-mega", "types": ["Water", "Psychic"], "boosts": ["Water", "Psychic"], "energy": 300, "raid": "Mega Raid", "stars": 4, "released": "August 22, 2026", "dps": 13.2, "moves": "Water Gun + Psychic", "artFallback": "starmie", "isNew": true, "attack": "Liquidation+", "rank": "B"},
  {"name": "Mega Pinsir", "art": "pinsir-mega", "types": ["Bug", "Flying"], "boosts": ["Bug", "Flying"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "May 11, 2023", "dps": 13.8, "moves": "Fury Cutter + X Scissor", "rank": "A"},
  {"name": "Mega Gyarados", "art": "gyarados-mega", "types": ["Water", "Dark"], "boosts": ["Water", "Dark"], "energy": 300, "raid": "Mega Raid", "stars": 4, "released": "February 9, 2021", "dps": 14.0, "moves": "Bite + Hydro Pump", "rank": "A"},
  {"name": "Mega Aerodactyl", "art": "aerodactyl-mega", "types": ["Rock", "Flying"], "boosts": ["Rock", "Flying"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "January 7, 2022", "dps": 13.2, "moves": "Rock Throw + Rock Slide", "rank": "B"},
  {"name": "Mega Dragonite", "art": "dragonite-mega", "types": ["Dragon", "Flying"], "boosts": ["Dragon", "Flying"], "energy": 300, "raid": "Mega Raid", "stars": 4, "released": "February 20, 2026", "dps": 15.5, "moves": "Dragon Tail + Draco Meteor", "legacy": true, "artFallback": "dragonite", "isNew": true, "attack": "Outrage+", "rank": "S"},
  {"name": "Mega Mewtwo X", "art": "mewtwo-mega-x", "types": ["Psychic", "Fighting"], "boosts": ["Psychic", "Fighting"], "energy": 7500, "raid": "Legendary Mega Raid", "stars": 6, "released": "May 24, 2026", "dps": 20.2, "moves": "Counter + Psystrike", "legacy": true, "attack": "Dynamic Punch+", "rank": "S"},
  {"name": "Mega Mewtwo Y", "art": "mewtwo-mega-y", "types": ["Psychic"], "boosts": ["Psychic"], "energy": 7500, "raid": "Legendary Mega Raid", "stars": 6, "released": "May 24, 2026", "dps": 21.1, "moves": "Psycho Cut + Psystrike", "legacy": true, "attack": "Future Sight+", "rank": "S"},
  {"name": "Mega Ampharos", "art": "ampharos-mega", "types": ["Electric", "Dragon"], "boosts": ["Electric", "Dragon"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "January 19, 2021", "dps": 13.9, "moves": "Volt Switch + Zap Cannon", "rank": "A"},
  {"name": "Mega Steelix", "art": "steelix-mega", "types": ["Steel", "Ground"], "boosts": ["Steel", "Ground"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "December 1, 2021", "dps": 10.3, "moves": "Iron Tail + Earthquake", "rank": "C"},
  {"name": "Mega Scizor", "art": "scizor-mega", "types": ["Bug", "Steel"], "boosts": ["Bug", "Steel"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "August 10, 2022", "dps": 11.8, "moves": "Bullet Punch + X Scissor", "rank": "C"},
  {"name": "Mega Heracross", "art": "heracross-mega", "types": ["Bug", "Fighting"], "boosts": ["Bug", "Fighting"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "April 13, 2024", "dps": 16.4, "moves": "Fury Cutter + Megahorn", "rank": "S"},
  {"name": "Mega Skarmory", "art": "skarmory-mega", "types": ["Steel", "Flying"], "boosts": ["Steel", "Flying"], "energy": 300, "raid": "Mega Raid", "stars": 4, "released": "June 27, 2026", "dps": 14.6, "moves": "Steel Wing + Brave Bird", "artFallback": "skarmory", "isNew": true, "attack": "Drill Peck+", "rank": "A"},
  {"name": "Mega Houndoom", "art": "houndoom-mega", "types": ["Dark", "Fire"], "boosts": ["Dark", "Fire"], "energy": 100, "raid": "Mega Raid", "stars": 4, "released": "October 1, 2020", "dps": 13.9, "moves": "Fire Fang + Foul Play", "attack": "Dark Pulse+", "rank": "A"},
  {"name": "Mega Tyranitar", "art": "tyranitar-mega", "types": ["Rock", "Dark"], "boosts": ["Rock", "Dark"], "energy": 300, "raid": "Mega Raid", "stars": 4, "released": "July 25, 2023", "dps": 14.6, "moves": "Bite + Brutal Swing", "rank": "A"},
  {"name": "Mega Sceptile", "art": "sceptile-mega", "types": ["Grass", "Dragon"], "boosts": ["Grass", "Dragon"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "December 3, 2022", "dps": 16.8, "moves": "Fury Cutter + Frenzy Plant", "legacy": true, "rank": "S"},
  {"name": "Mega Blaziken", "art": "blaziken-mega", "types": ["Fire", "Fighting"], "boosts": ["Fire", "Fighting"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "December 3, 2022", "dps": 18.5, "moves": "Counter + Aura Sphere", "rank": "S"},
  {"name": "Mega Swampert", "art": "swampert-mega", "types": ["Water", "Ground"], "boosts": ["Water", "Ground"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "December 3, 2022", "dps": 14.9, "moves": "Water Gun + Hydro Cannon", "legacy": true, "rank": "A"},
  {"name": "Mega Gardevoir", "art": "gardevoir-mega", "types": ["Psychic", "Fairy"], "boosts": ["Psychic", "Fairy"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "February 8, 2023", "dps": 15.7, "moves": "Confusion + Psychic", "rank": "S"},
  {"name": "Mega Sableye", "art": "sableye-mega", "types": ["Dark", "Ghost"], "boosts": ["Dark", "Ghost"], "energy": 100, "raid": "Mega Raid", "stars": 4, "released": "June 29, 2023", "dps": 7.9, "moves": "Shadow Claw + Foul Play", "rank": "D"},
  {"name": "Mega Mawile", "art": "mawile-mega", "types": ["Steel", "Fairy"], "boosts": ["Steel", "Fairy"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "October 12, 2024", "dps": 9.1, "moves": "Fairy Wind + Play Rough", "rank": "D"},
  {"name": "Mega Aggron", "art": "aggron-mega", "types": ["Steel"], "boosts": ["Steel"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "September 16, 2022", "dps": 11.9, "moves": "Iron Tail + Meteor Beam", "rank": "C"},
  {"name": "Mega Medicham", "art": "medicham-mega", "types": ["Fighting", "Psychic"], "boosts": ["Fighting", "Psychic"], "energy": 100, "raid": "Mega Raid", "stars": 4, "released": "March 8, 2023", "dps": 10.6, "moves": "Psycho Cut + Dynamic Punch", "rank": "C"},
  {"name": "Mega Manectric", "art": "manectric-mega", "types": ["Electric"], "boosts": ["Electric"], "energy": 100, "raid": "Mega Raid", "stars": 4, "released": "March 16, 2021", "dps": 14.9, "moves": "Thunder Fang + Wild Charge", "rank": "A"},
  {"name": "Mega Sharpedo", "art": "sharpedo-mega", "types": ["Water", "Dark"], "boosts": ["Water", "Dark"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "September 7, 2025", "dps": 13.9, "moves": "Bite + Hydro Pump", "rank": "A"},
  {"name": "Mega Camerupt", "art": "camerupt-mega", "types": ["Fire", "Ground"], "boosts": ["Fire", "Ground"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "September 28, 2025", "dps": 12.5, "moves": "Incinerate + Overheat", "rank": "B"},
  {"name": "Mega Altaria", "art": "altaria-mega", "types": ["Dragon", "Fairy"], "boosts": ["Dragon", "Fairy"], "energy": 300, "raid": "Mega Raid", "stars": 4, "released": "May 15, 2021", "dps": 10.9, "moves": "Dragon Breath + Dazzling Gleam", "rank": "C"},
  {"name": "Mega Banette", "art": "banette-mega", "types": ["Ghost"], "boosts": ["Ghost"], "energy": 100, "raid": "Mega Raid", "stars": 4, "released": "October 20, 2022", "dps": 15.1, "moves": "Hex + Shadow Ball", "rank": "A"},
  {"name": "Mega Absol", "art": "absol-mega", "types": ["Dark"], "boosts": ["Dark"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "October 22, 2021", "dps": 15.6, "moves": "Snarl + Brutal Swing", "legacy": true, "rank": "S"},
  {"name": "Mega Glalie", "art": "glalie-mega", "types": ["Ice"], "boosts": ["Ice"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "December 15, 2022", "dps": 11.9, "moves": "Ice Shard + Avalanche", "rank": "C"},
  {"name": "Mega Salamence", "art": "salamence-mega", "types": ["Dragon", "Flying"], "boosts": ["Dragon", "Flying"], "energy": 300, "raid": "Mega Raid", "stars": 4, "released": "January 10, 2023", "dps": 16.3, "moves": "Dragon Tail + Fly", "rank": "S"},
  {"name": "Mega Metagross", "art": "metagross-mega", "types": ["Steel", "Psychic"], "boosts": ["Steel", "Psychic"], "energy": 300, "raid": "Mega Raid", "stars": 4, "released": "October 4, 2025", "dps": 16.0, "moves": "Fury Cutter + Meteor Mash", "legacy": true, "rank": "S"},
  {"name": "Mega Latias", "art": "latias-mega", "types": ["Dragon", "Psychic"], "boosts": ["Dragon", "Psychic"], "energy": 300, "raid": "Legendary Mega Raid", "stars": 6, "released": "May 3, 2022", "dps": 14.8, "moves": "Dragon Breath + Aura Sphere", "rank": "A"},
  {"name": "Mega Latios", "art": "latios-mega", "types": ["Dragon", "Psychic"], "boosts": ["Dragon", "Psychic"], "energy": 300, "raid": "Legendary Mega Raid", "stars": 6, "released": "May 3, 2022", "dps": 16.2, "moves": "Zen Headbutt + Aura Sphere", "rank": "S"},
  {"name": "Primal Kyogre", "art": "kyogre-primal", "types": ["Water"], "boosts": ["Electric", "Water", "Bug"], "energy": 400, "raid": "Primal Raid", "stars": 5, "released": "February 18, 2023", "weatherBoost": true, "dps": 17.3, "moves": "Waterfall + Origin Pulse", "legacy": true, "rank": "S"},
  {"name": "Primal Groudon", "art": "groudon-primal", "types": ["Ground", "Fire"], "boosts": ["Grass", "Fire", "Ground"], "energy": 400, "raid": "Primal Raid", "stars": 5, "released": "February 18, 2023", "weatherBoost": true, "dps": 17.3, "moves": "Mud Shot + Precipice Blades", "legacy": true, "rank": "S"},
  {"name": "Mega Rayquaza", "art": "rayquaza-mega", "types": ["Dragon", "Flying"], "boosts": ["Flying", "Dragon", "Psychic"], "energy": 400, "raid": "Legendary Mega Raid", "stars": 6, "released": "August 4, 2023", "weatherBoost": true, "dps": 18.7, "moves": "Dragon Tail + Breaking Swipe", "legacy": true, "rank": "S"},
  {"name": "Mega Staraptor", "art": "staraptor-mega", "types": ["Fighting", "Flying"], "boosts": ["Fighting", "Flying"], "energy": 300, "raid": "Mega Raid", "stars": 4, "released": "September 19, 2026", "rank": "?", "artFallback": "staraptor", "isNew": true, "attack": "Brave Bird+"},
  {"name": "Mega Lopunny", "art": "lopunny-mega", "types": ["Normal", "Fighting"], "boosts": ["Normal", "Fighting"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "April 4, 2021", "dps": 14.7, "moves": "Pound + Focus Blast", "rank": "A"},
  {"name": "Mega Garchomp", "art": "garchomp-mega", "types": ["Dragon", "Ground"], "boosts": ["Dragon", "Ground"], "energy": 300, "raid": "Mega Raid", "stars": 4, "released": "November 11, 2023", "dps": 16.6, "moves": "Dragon Tail + Earthquake", "rank": "S"},
  {"name": "Mega Lucario", "art": "lucario-mega", "types": ["Fighting", "Steel"], "boosts": ["Fighting", "Steel"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "July 27, 2024", "dps": 18.3, "moves": "Force Palm + Aura Sphere", "legacy": true, "rank": "S"},
  {"name": "Mega Abomasnow", "art": "abomasnow-mega", "types": ["Grass", "Ice"], "boosts": ["Grass", "Ice"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "December 1, 2020", "dps": 11.7, "moves": "Leafage + Weather Ball Ice", "rank": "C"},
  {"name": "Mega Gallade", "art": "gallade-mega", "types": ["Psychic", "Fighting"], "boosts": ["Psychic", "Fighting"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "January 11, 2025", "dps": 15.9, "moves": "Low Kick + Psychic", "rank": "S"},
  {"name": "Mega Audino", "art": "audino-mega", "types": ["Normal", "Fairy"], "boosts": ["Normal", "Fairy"], "energy": 200, "raid": "Mega Raid", "stars": 4, "released": "April 5, 2025", "dps": 8.4, "moves": "Pound + Hyper Beam", "rank": "D"},
  {"name": "Mega Chandelure", "art": "chandelure-mega", "types": ["Ghost", "Fire"], "boosts": ["Ghost", "Fire"], "energy": 300, "raid": "Mega Raid", "stars": 4, "released": "April 5, 2025", "rank": "?", "artFallback": "chandelure", "isNew": true, "attack": "Ominous Wind+"},
  {"name": "Mega Chesnaught", "art": "chesnaught-mega", "types": ["Grass", "Fighting"], "boosts": ["Grass", "Fighting"], "energy": 300, "raid": "Mega Raid", "stars": 4, "released": "August 28, 2026", "dps": 13.5, "moves": "Low Kick + Frenzy Plant", "legacy": true, "artFallback": "chesnaught", "isNew": true, "attack": "Seed Bomb+", "rank": "B"},
  {"name": "Mega Delphox", "art": "delphox-mega", "types": ["Fire", "Psychic"], "boosts": ["Fire", "Psychic"], "energy": 300, "raid": "Mega Raid", "stars": 4, "released": "August 28, 2026", "dps": 17.4, "moves": "Fire Spin + Blast Burn", "legacy": true, "artFallback": "delphox", "isNew": true, "attack": "Mystical Fire+", "rank": "S"},
  {"name": "Mega Greninja", "art": "greninja-mega", "types": ["Water", "Dark"], "boosts": ["Water", "Dark"], "energy": 300, "raid": "Mega Raid", "stars": 4, "released": "August 28, 2026", "dps": 16.1, "moves": "Feint Attack + Hydro Cannon", "legacy": true, "artFallback": "greninja", "isNew": true, "attack": "Surf+", "rank": "S"},
  {"name": "Mega Malamar", "art": "malamar-mega", "types": ["Dark", "Psychic"], "boosts": ["Dark", "Psychic"], "energy": 300, "raid": "Mega Raid", "stars": 4, "released": "February 20, 2026", "dps": 10.3, "moves": "Psycho Cut + Foul Play", "artFallback": "malamar", "isNew": true, "attack": "Psybeam+", "rank": "C"},
  {"name": "Mega Diancie", "art": "diancie-mega", "types": ["Rock", "Fairy"], "boosts": ["Rock", "Fairy"], "energy": 300, "raid": "Legendary Mega Raid", "stars": 6, "released": "August 4, 2023", "dps": 15.7, "moves": "Rock Throw + Moonblast", "rank": "S"},
  {"name": "Mega Falinks", "art": "falinks-mega", "types": ["Fighting"], "boosts": ["Fighting"], "energy": 300, "raid": "Mega Raid", "stars": 4, "released": "May 23, 2026", "dps": 12.3, "moves": "Counter + Super Power", "artFallback": "falinks", "isNew": true, "attack": "Brick Break+", "rank": "B"}
];
